{
	"departmentsUrl":{
		"Пульмонологічне":"pulmo"
		,"Реанімаційне":"ait"
		,"ЕГ реанімація доросла":"ait"
		,"Хірургічне":"abdominal"
	}
	,"pl" : [ {
	"personal_username" : "Скакальська Л.І.",
	"personal_surname" : "Скакальська",
	"personal_name" : "Людмила",
	"personal_patronymic" : "Іванівна",
	"personal_id" : 2648,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 1,
	"department_name" : "Алергологiчне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "SkakalskaLI",
	"p1" : "С"
}, {
	"personal_username" : "Камінська О.Я.",
	"personal_surname" : "Камінська",
	"personal_name" : "Ольга",
	"personal_patronymic" : "Яківна",
	"personal_id" : 2649,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 1,
	"department_name" : "Алергологiчне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KaminskaOYa",
	"p1" : "К"
}, {
	"personal_username" : "Чорнобровий П.М.",
	"personal_surname" : "Чорнобровий",
	"personal_name" : "Павло",
	"personal_patronymic" : "Миколайович",
	"personal_id" : 2692,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 1,
	"department_name" : "Алергологiчне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ChornobrovijPM",
	"p1" : "Ч"
}, {
	"personal_username" : "Флаксемберг М.А.",
	"personal_surname" : "Флаксемберг",
	"personal_name" : "Майя",
	"personal_patronymic" : "Аркадіївна",
	"personal_id" : 2666,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 2,
	"department_name" : "Гінекологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "FlaksemberhMA",
	"p1" : "Ф"
}, {
	"personal_username" : "Антонецька Н.Б.",
	"personal_surname" : "Антонецька",
	"personal_name" : "Наталія",
	"personal_patronymic" : "Борисівна",
	"personal_id" : 2668,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 2,
	"department_name" : "Гінекологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "AntonetskaNB",
	"p1" : "А"
}, {
	"personal_username" : "Щепкіна Т.М.",
	"personal_surname" : "Щепкіна",
	"personal_name" : "Тамара",
	"personal_patronymic" : "Михалівна",
	"personal_id" : 2674,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 2,
	"department_name" : "Гінекологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ShchepkinaTM",
	"p1" : "Щ"
}, {
	"personal_username" : "Онишко В.Ю.",
	"personal_surname" : "Онишко",
	"personal_name" : "Віктор",
	"personal_patronymic" : "Юхимович",
	"personal_id" : 2694,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 2,
	"department_name" : "Гінекологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "OnishkoVYu",
	"p1" : "О"
}, {
	"personal_username" : "Павлюк Т.В.",
	"personal_surname" : "Павлюк",
	"personal_name" : "Тамара",
	"personal_patronymic" : "Вікторівна",
	"personal_id" : 130,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 3,
	"department_name" : "Гастроентерологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PavlyukTV",
	"p1" : "П"
}, {
	"personal_username" : "Афійчук Л.В.",
	"personal_surname" : "Афійчук",
	"personal_name" : "Людмила",
	"personal_patronymic" : "Василівна",
	"personal_id" : 131,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 3,
	"department_name" : "Гастроентерологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "AfijchukLV",
	"p1" : "А"
}, {
	"personal_username" : "Мацишина Л.В.",
	"personal_surname" : "Мацишина",
	"personal_name" : "Людмила",
	"personal_patronymic" : "Володимирівна",
	"personal_id" : 133,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 3,
	"department_name" : "Гастроентерологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MatsishinaLV",
	"p1" : "М"
}, {
	"personal_username" : "Олешко Л.В.",
	"personal_surname" : "Олешко",
	"personal_name" : "Любов",
	"personal_patronymic" : "Василівна",
	"personal_id" : 2678,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 3,
	"department_name" : "Гастроентерологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "OleshkoLV",
	"p1" : "О"
}, {
	"personal_username" : "Кіндзерська А.В.",
	"personal_surname" : "Кіндзерська",
	"personal_name" : "Ала",
	"personal_patronymic" : "Василівна",
	"personal_id" : 2680,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 3,
	"department_name" : "Гастроентерологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KindzerskaAV",
	"p1" : "К"
}, {
	"personal_username" : "Повх В.В.",
	"personal_surname" : "Повх",
	"personal_name" : "Віта",
	"personal_patronymic" : "Володимирівна",
	"personal_id" : 2681,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 3,
	"department_name" : "Гастроентерологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PovkhVV",
	"p1" : "П"
}, {
	"personal_username" : "Мацишена Л.Д.",
	"personal_surname" : "Мацишена",
	"personal_name" : "Людмила",
	"personal_patronymic" : "Дмитрівна",
	"personal_id" : 2693,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 3,
	"department_name" : "Гастроентерологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MatsishenaLD",
	"p1" : "М"
}, {
	"personal_username" : "Алешко Л.В.",
	"personal_surname" : "Алешко",
	"personal_name" : "Любов",
	"personal_patronymic" : "Василівна",
	"personal_id" : 132,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 3,
	"department_name" : "Гастроентерологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "AleshkoLV",
	"p1" : "А"
}, {
	"personal_username" : "Бобровник  А.О.",
	"personal_surname" : "Бобровник",
	"personal_name" : "Андрій",
	"personal_patronymic" : "Олександрович",
	"personal_id" : 2670,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 4,
	"department_name" : "Гематологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "BobrovnikAO",
	"p1" : "Б"
}, {
	"personal_username" : "Підмурняк Н.М.",
	"personal_surname" : "Підмурняк",
	"personal_name" : "Надія",
	"personal_patronymic" : "Миколаївна",
	"personal_id" : 2671,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 4,
	"department_name" : "Гематологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PidmurnyakNM",
	"p1" : "П"
}, {
	"personal_username" : "Пещинська Н.С.",
	"personal_surname" : "Пещинська",
	"personal_name" : "Надія",
	"personal_patronymic" : "Сафонівна",
	"personal_id" : 2672,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 4,
	"department_name" : "Гематологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PeshchinskaNS",
	"p1" : "П"
}, {
	"personal_username" : "Мороз Л.П.",
	"personal_surname" : "Мороз",
	"personal_name" : "Лариса",
	"personal_patronymic" : "Петрівна",
	"personal_id" : 2673,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 4,
	"department_name" : "Гематологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MorozLP",
	"p1" : "М"
}, {
	"personal_username" : "Бобровник А.О.",
	"personal_surname" : "Бобровник",
	"personal_name" : "Андрій",
	"personal_patronymic" : "Олександрович",
	"personal_id" : 2675,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 4,
	"department_name" : "Гематологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "BobrovnikAO",
	"p1" : "Б"
}, {
	"personal_username" : "Щепіна Т.М.",
	"personal_surname" : "Щепіна",
	"personal_name" : "Тамара",
	"personal_patronymic" : "Михалівна",
	"personal_id" : 2696,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 4,
	"department_name" : "Гематологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ShchepinaTM",
	"p1" : "Щ"
}, {
	"personal_username" : "Онуфран В.І.",
	"personal_surname" : "Онуфран",
	"personal_name" : "Віталій",
	"personal_patronymic" : "Іванович",
	"personal_id" : 139,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 5,
	"department_name" : "Детоксикації",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "OnufranVI",
	"p1" : "О"
}, {
	"personal_username" : "Педосюк Т.О.",
	"personal_surname" : "Педосюк",
	"personal_name" : "Тетяна",
	"personal_patronymic" : "Олександрівна",
	"personal_id" : 140,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 5,
	"department_name" : "Детоксикації",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PedosyukTO",
	"p1" : "П"
}, {
	"personal_username" : "Жила Н.В.",
	"personal_surname" : "Жила",
	"personal_name" : "Наталія",
	"personal_patronymic" : "Володимирівна",
	"personal_id" : 141,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 5,
	"department_name" : "Детоксикації",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ZhilaNV",
	"p1" : "Ж"
}, {
	"personal_username" : "Бондарук О.З.",
	"personal_surname" : "Бондарук",
	"personal_name" : "Ольга",
	"personal_patronymic" : "Зіновіївна",
	"personal_id" : 142,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 5,
	"department_name" : "Детоксикації",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "BondarukOZ",
	"p1" : "Б"
}, {
	"personal_username" : "Щербатюк М.І.",
	"personal_surname" : "Щербатюк",
	"personal_name" : "Микола",
	"personal_patronymic" : "Іванович",
	"personal_id" : 143,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 5,
	"department_name" : "Детоксикації",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ShcherbatyukMI",
	"p1" : "Щ"
}, {
	"personal_username" : "Волошина І.М.",
	"personal_surname" : "Волошина",
	"personal_name" : "Інна",
	"personal_patronymic" : "Михайлівна",
	"personal_id" : 144,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 5,
	"department_name" : "Детоксикації",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "VoloshinaIM",
	"p1" : "В"
}, {
	"personal_username" : "Косташ В.М.",
	"personal_surname" : "Косташ",
	"personal_name" : "Віктор",
	"personal_patronymic" : "Михайлович",
	"personal_id" : 176,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 5,
	"department_name" : "Детоксикації",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KostashVM",
	"p1" : "К"
}, {
	"personal_username" : "Гончарук В.М.",
	"personal_surname" : "Гончарук",
	"personal_name" : "Володимир",
	"personal_patronymic" : "МИхайлович",
	"personal_id" : 177,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 5,
	"department_name" : "Детоксикації",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "HoncharukVM",
	"p1" : "Г"
}, {
	"personal_username" : "Середа І.В.",
	"personal_surname" : "Середа",
	"personal_name" : "Ірина",
	"personal_patronymic" : "Василівна",
	"personal_id" : 178,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 5,
	"department_name" : "Детоксикації",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "SeredaIV",
	"p1" : "С"
}, {
	"personal_username" : "Малоголовка О.А.",
	"personal_surname" : "Малоголовка",
	"personal_name" : "Олександр",
	"personal_patronymic" : "Андрійович",
	"personal_id" : 179,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 5,
	"department_name" : "Детоксикації",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MaloholovkaOA",
	"p1" : "М"
}, {
	"personal_username" : "Білобрицький В.Г.",
	"personal_surname" : "Білобрицький",
	"personal_name" : "Віктор",
	"personal_patronymic" : "Григорович",
	"personal_id" : 180,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 5,
	"department_name" : "Детоксикації",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "BilobritskijVH",
	"p1" : "Б"
}, {
	"personal_username" : "Дмитришин М.А.",
	"personal_surname" : "Дмитришин",
	"personal_name" : "Микола",
	"personal_patronymic" : "Андрійович",
	"personal_id" : 189,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 5,
	"department_name" : "Детоксикації",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "DmitrishinMA",
	"p1" : "Д"
}, {
	"personal_username" : "Кожановська А.В.",
	"personal_surname" : "Кожановська",
	"personal_name" : "Альоша",
	"personal_patronymic" : "Володимирівна",
	"personal_id" : 200,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 5,
	"department_name" : "Детоксикації",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KozhanovskaAV",
	"p1" : "К"
}, {
	"personal_username" : "Вакуленко В.О.",
	"personal_surname" : "Вакуленко",
	"personal_name" : "Василь",
	"personal_patronymic" : "Олександрович",
	"personal_id" : 2703,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 5,
	"department_name" : "Детоксикації",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "VakulenkoVO",
	"p1" : "В"
}, {
	"personal_username" : "Грач О.І.",
	"personal_surname" : "Грач",
	"personal_name" : "Олександр",
	"personal_patronymic" : "Іванович",
	"personal_id" : 165,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 6,
	"department_name" : "ЕГ реанімація доросла",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "HrachOI",
	"p1" : "Г"
}, {
	"personal_username" : "Литовка В.О.",
	"personal_surname" : "Литовка",
	"personal_name" : "Вікторія",
	"personal_patronymic" : "Олександрівна",
	"personal_id" : 185,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 6,
	"department_name" : "ЕГ реанімація доросла",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "LitovkaVO",
	"p1" : "Л"
}, {
	"personal_username" : "Іванюк С.В.",
	"personal_surname" : "Іванюк",
	"personal_name" : "Світлана",
	"personal_patronymic" : "Володимирівна",
	"personal_id" : 187,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 6,
	"department_name" : "ЕГ реанімація доросла",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "IvanyukSV",
	"p1" : "І"
}, {
	"personal_username" : "Данилюк С.В.",
	"personal_surname" : "Данилюк",
	"personal_name" : "Сергій",
	"personal_patronymic" : "Віталійович",
	"personal_id" : 191,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 6,
	"department_name" : "ЕГ реанімація доросла",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "DanilyukSV",
	"p1" : "Д"
}, {
	"personal_username" : "Чолій В.М.",
	"personal_surname" : "Чолій",
	"personal_name" : "Василь",
	"personal_patronymic" : "Михайлович",
	"personal_id" : 201,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 6,
	"department_name" : "ЕГ реанімація доросла",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "CholijVM",
	"p1" : "Ч"
}, {
	"personal_username" : "Осадчий В.В.",
	"personal_surname" : "Осадчий",
	"personal_name" : "Василь",
	"personal_patronymic" : "Васильович",
	"personal_id" : 202,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 6,
	"department_name" : "ЕГ реанімація доросла",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "OsadchijVV",
	"p1" : "О"
}, {
	"personal_username" : "Поліщук І.В.",
	"personal_surname" : "Поліщук",
	"personal_name" : "Інна",
	"personal_patronymic" : "Володимирівна",
	"personal_id" : 203,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 6,
	"department_name" : "ЕГ реанімація доросла",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PolishchukIV",
	"p1" : "П"
}, {
	"personal_username" : "Паляниця Н.М.",
	"personal_surname" : "Паляниця",
	"personal_name" : "Наталія",
	"personal_patronymic" : "Миколаївна",
	"personal_id" : 204,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 6,
	"department_name" : "ЕГ реанімація доросла",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PalyanitsyaNM",
	"p1" : "П"
}, {
	"personal_username" : "Мельник Л.І.",
	"personal_surname" : "Мельник",
	"personal_name" : "Людмила",
	"personal_patronymic" : "Іванівна ",
	"personal_id" : 2707,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 6,
	"department_name" : "ЕГ реанімація доросла",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MelnikLI",
	"p1" : "М"
}, {
	"personal_username" : "Рубас Л.В.",
	"personal_surname" : "Рубас",
	"personal_name" : "Лариса",
	"personal_patronymic" : "Вікторівна",
	"personal_id" : 145,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 7,
	"department_name" : "ЕГПВ та Н",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "RubasLV",
	"p1" : "Р"
}, {
	"personal_username" : "Могильницька Л.А.",
	"personal_surname" : "Могильницька",
	"personal_name" : "Лілія",
	"personal_patronymic" : "Анатолівна",
	"personal_id" : 2682,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 8,
	"department_name" : "Ендокринологія",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MohilnitskaLA",
	"p1" : "М"
}, {
	"personal_username" : "Путасевич Н.М.",
	"personal_surname" : "Путасевич",
	"personal_name" : "Надія",
	"personal_patronymic" : "Михалівна",
	"personal_id" : 2683,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 8,
	"department_name" : "Ендокринологія",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PutasevichNM",
	"p1" : "П"
}, {
	"personal_username" : "Філик М.А.",
	"personal_surname" : "Філик",
	"personal_name" : "Майя",
	"personal_patronymic" : "Арсентівна",
	"personal_id" : 2684,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 8,
	"department_name" : "Ендокринологія",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "FilikMA",
	"p1" : "Ф"
}, {
	"personal_username" : "Кононенко В.Х.",
	"personal_surname" : "Кононенко",
	"personal_name" : "Володимир",
	"personal_patronymic" : "Харитонович",
	"personal_id" : 2685,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 8,
	"department_name" : "Ендокринологія",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KononenkoVKh",
	"p1" : "К"
}, {
	"personal_username" : "Заярнюк С.С.",
	"personal_surname" : "Заярнюк",
	"personal_name" : "Світлана",
	"personal_patronymic" : "Сергіївна",
	"personal_id" : 2686,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 8,
	"department_name" : "Ендокринологія",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ZayarnyukSS",
	"p1" : "З"
}, {
	"personal_username" : "Вольська Т.В.",
	"personal_surname" : "Вольська",
	"personal_name" : "Тетяна",
	"personal_patronymic" : "Василівна",
	"personal_id" : 2687,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 8,
	"department_name" : "Ендокринологія",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "VolskaTV",
	"p1" : "В"
}, {
	"personal_username" : "Кобунько В.М.",
	"personal_surname" : "Кобунько",
	"personal_name" : "Валентина",
	"personal_patronymic" : "Миколаївна",
	"personal_id" : 2688,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 8,
	"department_name" : "Ендокринологія",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KobunkoVM",
	"p1" : "К"
}, {
	"personal_username" : "Кутсевич Н.М.",
	"personal_surname" : "Кутсевич",
	"personal_name" : "Надія",
	"personal_patronymic" : "Михалівна",
	"personal_id" : 2701,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 8,
	"department_name" : "Ендокринологія",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KutsevichNM",
	"p1" : "К"
}, {
	"personal_username" : "Кутасевич Н.М.",
	"personal_surname" : "Кутасевич",
	"personal_name" : "Надія",
	"personal_patronymic" : "Михалівна",
	"personal_id" : 2702,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 8,
	"department_name" : "Ендокринологія",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KutasevichNM",
	"p1" : "К"
}, {
	"personal_username" : "Сухарєв В.А.",
	"personal_surname" : "Сухарєв",
	"personal_name" : "Валерій",
	"personal_patronymic" : "Анатолійович",
	"personal_id" : 265,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 9,
	"department_name" : "Кардіохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "SukharyevVA",
	"p1" : "С"
}, {
	"personal_username" : "Сич О.О.",
	"personal_surname" : "Сич",
	"personal_name" : "Олексій",
	"personal_patronymic" : "Олександрович",
	"personal_id" : 266,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 9,
	"department_name" : "Кардіохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "SichOO",
	"p1" : "С"
}, {
	"personal_username" : "Шимків А.П.",
	"personal_surname" : "Шимків",
	"personal_name" : "Андрій",
	"personal_patronymic" : "Петрович",
	"personal_id" : 267,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 9,
	"department_name" : "Кардіохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ShimkivAP",
	"p1" : "Ш"
}, {
	"personal_username" : "Швець С.В.",
	"personal_surname" : "Швець",
	"personal_name" : "Сергій",
	"personal_patronymic" : "Васильович",
	"personal_id" : 268,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 9,
	"department_name" : "Кардіохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ShvetsSV",
	"p1" : "Ш"
}, {
	"personal_username" : "Пискливець З.Ст.",
	"personal_surname" : "Пискливець",
	"personal_name" : "Зорян",
	"personal_patronymic" : "Степанович",
	"personal_id" : 270,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 9,
	"department_name" : "Кардіохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PisklivetsZSt",
	"p1" : "П"
}, {
	"personal_username" : "Мазур Л.М.",
	"personal_surname" : "Мазур",
	"personal_name" : "Лариса",
	"personal_patronymic" : "Миколаївна",
	"personal_id" : 271,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 9,
	"department_name" : "Кардіохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MazurLM",
	"p1" : "М"
}, {
	"personal_username" : "Мельник Л.М.",
	"personal_surname" : "Мельник",
	"personal_name" : "Людмила",
	"personal_patronymic" : "Михайлівна",
	"personal_id" : 272,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 9,
	"department_name" : "Кардіохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MelnikLM",
	"p1" : "М"
}, {
	"personal_username" : "Киричук О.В.",
	"personal_surname" : "Киричук",
	"personal_name" : "Ольга",
	"personal_patronymic" : "Василівна",
	"personal_id" : 193,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 10,
	"department_name" : "Кардіореанімація",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KirichukOV",
	"p1" : "К"
}, {
	"personal_username" : "Тищенко І.С.",
	"personal_surname" : "Тищенко",
	"personal_name" : "Ірена",
	"personal_patronymic" : "Станіславівна",
	"personal_id" : 196,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 10,
	"department_name" : "Кардіореанімація",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "TishchenkoIS",
	"p1" : "Т"
}, {
	"personal_username" : "Шалавінський М.П.",
	"personal_surname" : "Шалавінський",
	"personal_name" : "Микола",
	"personal_patronymic" : "Петрович",
	"personal_id" : 197,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 10,
	"department_name" : "Кардіореанімація",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ShalavinskijMP",
	"p1" : "Ш"
}, {
	"personal_username" : "Невеличук Т.А.",
	"personal_surname" : "Невеличук",
	"personal_name" : "Тарас",
	"personal_patronymic" : "Анатолійович",
	"personal_id" : 275,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 10,
	"department_name" : "Кардіореанімація",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "NevelichukTA",
	"p1" : "Н"
}, {
	"personal_username" : "Терехівська О.В.",
	"personal_surname" : "Терехівська",
	"personal_name" : "Ольга",
	"personal_patronymic" : "Володимирівна",
	"personal_id" : 2665,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 10,
	"department_name" : "Кардіореанімація",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "TerekhivskaOV",
	"p1" : "Т"
}, {
	"personal_username" : "Степанюк Л.В.",
	"personal_surname" : "Степанюк",
	"personal_name" : "Людмила",
	"personal_patronymic" : "Володимирівна",
	"personal_id" : 304,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 11,
	"department_name" : "Неврологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "StepanyukLV",
	"p1" : "С"
}, {
	"personal_username" : "Григор'єва П.В.",
	"personal_surname" : "Григор'єва",
	"personal_name" : "Павліна",
	"personal_patronymic" : "Володимирівна",
	"personal_id" : 303,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 11,
	"department_name" : "Неврологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "HrihoryevaPV",
	"p1" : "Г"
}, {
	"personal_username" : "Кравчук В.О.",
	"personal_surname" : "Кравчук",
	"personal_name" : "Вікторія",
	"personal_patronymic" : "Олександрівна",
	"personal_id" : 305,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 11,
	"department_name" : "Неврологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KravchukVO",
	"p1" : "К"
}, {
	"personal_username" : "Гавловський В.К.",
	"personal_surname" : "Гавловський",
	"personal_name" : "Вадим",
	"personal_patronymic" : "Казимирович",
	"personal_id" : 302,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 11,
	"department_name" : "Неврологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "HavlovskijVK",
	"p1" : "Г"
}, {
	"personal_username" : "Євдохович З.В.",
	"personal_surname" : "Євдохович",
	"personal_name" : "Зоряна",
	"personal_patronymic" : "Володимирівна",
	"personal_id" : 297,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 11,
	"department_name" : "Неврологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "YevdokhovichZV",
	"p1" : "Є"
}, {
	"personal_username" : "Білоус Г.А.",
	"personal_surname" : "Білоус",
	"personal_name" : "Генадій",
	"personal_patronymic" : "Андрійович",
	"personal_id" : 295,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 11,
	"department_name" : "Неврологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "BilousHA",
	"p1" : "Б"
}, {
	"personal_username" : "Ковтун О.П.",
	"personal_surname" : "Ковтун",
	"personal_name" : "Оксана",
	"personal_patronymic" : "Петрівна",
	"personal_id" : 296,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 11,
	"department_name" : "Неврологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KovtunOP",
	"p1" : "К"
}, {
	"personal_username" : "Верхола І.В.",
	"personal_surname" : "Верхола",
	"personal_name" : "Ірина",
	"personal_patronymic" : "Василівна",
	"personal_id" : 298,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 11,
	"department_name" : "Неврологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "VerkholaIV",
	"p1" : "В"
}, {
	"personal_username" : "Бальжик Т.Л.",
	"personal_surname" : "Бальжик",
	"personal_name" : "Тетяна",
	"personal_patronymic" : "Леонідівна",
	"personal_id" : 299,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 11,
	"department_name" : "Неврологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "BalzhikTL",
	"p1" : "Б"
}, {
	"personal_username" : "Омелянчук А.Г.",
	"personal_surname" : "Омелянчук",
	"personal_name" : "Анатолій",
	"personal_patronymic" : "Георгійович",
	"personal_id" : 300,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 11,
	"department_name" : "Неврологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "OmelyanchukAH",
	"p1" : "О"
}, {
	"personal_username" : "Лісова Н.Я.",
	"personal_surname" : "Лісова",
	"personal_name" : "Надія",
	"personal_patronymic" : "Яківна",
	"personal_id" : 301,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 11,
	"department_name" : "Неврологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "LisovaNYa",
	"p1" : "Л"
}, {
	"personal_username" : "Літучий В.М.",
	"personal_surname" : "Літучий",
	"personal_name" : "Віталій",
	"personal_patronymic" : "Мусійович",
	"personal_id" : 231,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 12,
	"department_name" : "Нейрохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "LituchijVM",
	"p1" : "Л"
}, {
	"personal_username" : "Тарнович Ю.М.",
	"personal_surname" : "Тарнович",
	"personal_name" : "Юрій",
	"personal_patronymic" : "Миронович",
	"personal_id" : 232,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 12,
	"department_name" : "Нейрохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "TarnovichYuM",
	"p1" : "Т"
}, {
	"personal_username" : "Ткач Б.В.",
	"personal_surname" : "Ткач",
	"personal_name" : "Борис",
	"personal_patronymic" : "Васильович",
	"personal_id" : 233,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 12,
	"department_name" : "Нейрохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "TkachBV",
	"p1" : "Т"
}, {
	"personal_username" : "Сарнацький В.В.",
	"personal_surname" : "Сарнацький",
	"personal_name" : "Вадим",
	"personal_patronymic" : "Вадимович",
	"personal_id" : 234,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 12,
	"department_name" : "Нейрохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "SarnatskijVV",
	"p1" : "С"
}, {
	"personal_username" : "Кримський В.С.",
	"personal_surname" : "Кримський",
	"personal_name" : "Віктор",
	"personal_patronymic" : "Станіславович",
	"personal_id" : 235,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 12,
	"department_name" : "Нейрохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KrimskijVS",
	"p1" : "К"
}, {
	"personal_username" : "Мороз О.А.",
	"personal_surname" : "Мороз",
	"personal_name" : "Олександр",
	"personal_patronymic" : "Анатолійович",
	"personal_id" : 236,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 12,
	"department_name" : "Нейрохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MorozOA",
	"p1" : "М"
}, {
	"personal_username" : "Чернецький В.В.",
	"personal_surname" : "Чернецький",
	"personal_name" : "Вадим",
	"personal_patronymic" : "Віталійович",
	"personal_id" : 237,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 12,
	"department_name" : "Нейрохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ChernetskijVV",
	"p1" : "Ч"
}, {
	"personal_username" : "Лозинський А.В.",
	"personal_surname" : "Лозинський",
	"personal_name" : "Анатолій",
	"personal_patronymic" : "Валерійович",
	"personal_id" : 238,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 12,
	"department_name" : "Нейрохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "LozinskijAV",
	"p1" : "Л"
}, {
	"personal_username" : "Стецьків Т.П.",
	"personal_surname" : "Стецьків",
	"personal_name" : "Тетяна",
	"personal_patronymic" : "Петрівна",
	"personal_id" : 245,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 12,
	"department_name" : "Нейрохірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "StetskivTP",
	"p1" : "С"
}, {
	"personal_username" : "Білоус Л.М.",
	"personal_surname" : "Білоус",
	"personal_name" : "Лідія",
	"personal_patronymic" : "Михайлівна",
	"personal_id" : 136,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 13,
	"department_name" : "Нефрологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "BilousLM",
	"p1" : "Б"
}, {
	"personal_username" : "Кушнір Н.І.",
	"personal_surname" : "Кушнір",
	"personal_name" : "Наталія",
	"personal_patronymic" : "Іванівна",
	"personal_id" : 135,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 13,
	"department_name" : "Нефрологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KushnirNI",
	"p1" : "К"
}, {
	"personal_username" : "Тоцька О.Л.",
	"personal_surname" : "Тоцька",
	"personal_name" : "Олена",
	"personal_patronymic" : "Леонідівна",
	"personal_id" : 137,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 13,
	"department_name" : "Нефрологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "TotskaOL",
	"p1" : "Т"
}, {
	"personal_username" : "Грановська Г.В.",
	"personal_surname" : "Грановська",
	"personal_name" : "Галина",
	"personal_patronymic" : "Віталівна",
	"personal_id" : 2700,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 13,
	"department_name" : "Нефрологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "HranovskaHV",
	"p1" : "Г"
}, {
	"personal_username" : "Алешко Н.Ю.",
	"personal_surname" : "Алешко",
	"personal_name" : "Наталя",
	"personal_patronymic" : "Юліанівна",
	"personal_id" : 2713,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 13,
	"department_name" : "Нефрологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "AleshkoNYu",
	"p1" : "А"
}, {
	"personal_username" : "Максімов С.Л.",
	"personal_surname" : "Максімов",
	"personal_name" : "Сергій",
	"personal_patronymic" : "Леонідович",
	"personal_id" : 183,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 14,
	"department_name" : "Опікове",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MaksimovSL",
	"p1" : "М"
}, {
	"personal_username" : "Каритун Н.П.",
	"personal_surname" : "Каритун",
	"personal_name" : "Наталія",
	"personal_patronymic" : "Петрівна",
	"personal_id" : 188,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 14,
	"department_name" : "Опікове",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KaritunNP",
	"p1" : "К"
}, {
	"personal_username" : "Кабачинський М.К.",
	"personal_surname" : "Кабачинський",
	"personal_name" : "Максим",
	"personal_patronymic" : "Констянтинович",
	"personal_id" : 190,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 14,
	"department_name" : "Опікове",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KabachinskijMK",
	"p1" : "К"
}, {
	"personal_username" : "Вакулено В.О.",
	"personal_surname" : "Вакулено",
	"personal_name" : "Василь",
	"personal_patronymic" : "Олександрович",
	"personal_id" : 192,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 14,
	"department_name" : "Опікове",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "VakulenoVO",
	"p1" : "В"
}, {
	"personal_username" : "Прозорський І.В.",
	"personal_surname" : "Прозорський",
	"personal_name" : "Іван",
	"personal_patronymic" : "Володимирович",
	"personal_id" : 198,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 14,
	"department_name" : "Опікове",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ProzorskijIV",
	"p1" : "П"
}, {
	"personal_username" : "Пацаранюк О.Д.",
	"personal_surname" : "Пацаранюк",
	"personal_name" : "Олександр",
	"personal_patronymic" : "Дмитрович",
	"personal_id" : 250,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 14,
	"department_name" : "Опікове",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PatsaranyukOD",
	"p1" : "П"
}, {
	"personal_username" : "Хуторцова О.А.",
	"personal_surname" : "Хуторцова",
	"personal_name" : "Оксана",
	"personal_patronymic" : "Анатоліївна",
	"personal_id" : 251,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 14,
	"department_name" : "Опікове",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KhutortsovaOA",
	"p1" : "Х"
}, {
	"personal_username" : "Марущак В.П.",
	"personal_surname" : "Марущак",
	"personal_name" : "Віталій",
	"personal_patronymic" : "Пилипович",
	"personal_id" : 253,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 15,
	"department_name" : "Ортопедичне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MarushchakVP",
	"p1" : "М"
}, {
	"personal_username" : "Кикилик В.М.",
	"personal_surname" : "Кикилик",
	"personal_name" : "Володимир",
	"personal_patronymic" : "Миколайович",
	"personal_id" : 254,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 15,
	"department_name" : "Ортопедичне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KikilikVM",
	"p1" : "К"
}, {
	"personal_username" : "Зав'ялець І.Т.",
	"personal_surname" : "Зав'ялець",
	"personal_name" : "Іван",
	"personal_patronymic" : "Тодорович",
	"personal_id" : 255,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 15,
	"department_name" : "Ортопедичне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ZavyaletsIT",
	"p1" : "З"
}, {
	"personal_username" : "Машевський А.С.",
	"personal_surname" : "Машевський",
	"personal_name" : "Андрій",
	"personal_patronymic" : "Станіславович",
	"personal_id" : 256,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 15,
	"department_name" : "Ортопедичне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MashevskijAS",
	"p1" : "М"
}, {
	"personal_username" : "Марущак В.В.",
	"personal_surname" : "Марущак",
	"personal_name" : "Віталій",
	"personal_patronymic" : "Віталійович",
	"personal_id" : 257,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 15,
	"department_name" : "Ортопедичне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MarushchakVV",
	"p1" : "М"
}, {
	"personal_username" : "Зав'ялець Л.І.",
	"personal_surname" : "Зав'ялець",
	"personal_name" : "Любомир",
	"personal_patronymic" : "Іванович",
	"personal_id" : 258,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 15,
	"department_name" : "Ортопедичне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ZavyaletsLI",
	"p1" : "З"
}, {
	"personal_username" : "Габінет В.Д.",
	"personal_surname" : "Габінет",
	"personal_name" : "Віталій",
	"personal_patronymic" : "Дмитрович",
	"personal_id" : 259,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 15,
	"department_name" : "Ортопедичне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "HabinetVD",
	"p1" : "Г"
}, {
	"personal_username" : "Витвицький В.Б.",
	"personal_surname" : "Витвицький",
	"personal_name" : "Василь",
	"personal_patronymic" : "Богданович",
	"personal_id" : 260,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 15,
	"department_name" : "Ортопедичне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "VitvitskijVB",
	"p1" : "В"
}, {
	"personal_username" : "Загродський О.В.",
	"personal_surname" : "Загродський",
	"personal_name" : "Олександр",
	"personal_patronymic" : "Вікторович",
	"personal_id" : 2652,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 15,
	"department_name" : "Ортопедичне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ZahrodskijOV",
	"p1" : "З"
}, {
	"personal_username" : "Курило І.В.",
	"personal_surname" : "Курило",
	"personal_name" : "Ігор",
	"personal_patronymic" : "Віталійович",
	"personal_id" : 2656,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 15,
	"department_name" : "Ортопедичне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KuriloIV",
	"p1" : "К"
}, {
	"personal_username" : "Лукаш К.В.",
	"personal_surname" : "Лукаш",
	"personal_name" : "Констянтин",
	"personal_patronymic" : "Володимирович",
	"personal_id" : 2657,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 15,
	"department_name" : "Ортопедичне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "LukashKV",
	"p1" : "Л"
}, {
	"personal_username" : "Курило І.І.",
	"personal_surname" : "Курило",
	"personal_name" : "Ігор",
	"personal_patronymic" : "Іванович",
	"personal_id" : 2664,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 15,
	"department_name" : "Ортопедичне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KuriloII",
	"p1" : "К"
}, {
	"personal_username" : "Мельник Л.П.",
	"personal_surname" : "Мельник",
	"personal_name" : "Леонід",
	"personal_patronymic" : "Петрович",
	"personal_id" : 2709,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 15,
	"department_name" : "Ортопедичне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MelnikLP",
	"p1" : "М"
}, {
	"personal_username" : "Дарманська І.А.",
	"personal_surname" : "Дарманська",
	"personal_name" : "Ірина",
	"personal_patronymic" : "Анатоліївна",
	"personal_id" : 286,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 16,
	"department_name" : "Офтальмологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "DarmanskaIA",
	"p1" : "Д"
}, {
	"personal_username" : "Кульбаба О.Г.",
	"personal_surname" : "Кульбаба",
	"personal_name" : "Олександр",
	"personal_patronymic" : "Григорович",
	"personal_id" : 287,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 16,
	"department_name" : "Офтальмологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KulbabaOH",
	"p1" : "К"
}, {
	"personal_username" : "Козак І.І.",
	"personal_surname" : "Козак",
	"personal_name" : "Ірина",
	"personal_patronymic" : "Іванівна",
	"personal_id" : 288,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 16,
	"department_name" : "Офтальмологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KozakII",
	"p1" : "К"
}, {
	"personal_username" : "Каплінська Л.В.",
	"personal_surname" : "Каплінська",
	"personal_name" : "Людмила",
	"personal_patronymic" : "Василівна",
	"personal_id" : 289,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 16,
	"department_name" : "Офтальмологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KaplinskaLV",
	"p1" : "К"
}, {
	"personal_username" : "Кириченко О.В.",
	"personal_surname" : "Кириченко",
	"personal_name" : "Ольга",
	"personal_patronymic" : "Володимирівна",
	"personal_id" : 291,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 16,
	"department_name" : "Офтальмологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KirichenkoOV",
	"p1" : "К"
}, {
	"personal_username" : "Шамаріна І.Ю.",
	"personal_surname" : "Шамаріна",
	"personal_name" : "Ірина",
	"personal_patronymic" : "Юріївна",
	"personal_id" : 290,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 16,
	"department_name" : "Офтальмологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ShamarinaIYu",
	"p1" : "Ш"
}, {
	"personal_username" : "Філатова Т.В.",
	"personal_surname" : "Філатова",
	"personal_name" : "Тетяна",
	"personal_patronymic" : "Вікторівна",
	"personal_id" : 292,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 16,
	"department_name" : "Офтальмологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "FilatovaTV",
	"p1" : "Ф"
}, {
	"personal_username" : "Коломієць О.В.",
	"personal_surname" : "Коломієць",
	"personal_name" : "Ольга",
	"personal_patronymic" : "Володимирівна",
	"personal_id" : 293,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 16,
	"department_name" : "Офтальмологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KolomiyetsOV",
	"p1" : "К"
}, {
	"personal_username" : "Ференс Т.В.",
	"personal_surname" : "Ференс",
	"personal_name" : "Тетяна",
	"personal_patronymic" : "Віталіївна",
	"personal_id" : 2647,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 16,
	"department_name" : "Офтальмологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "FerensTV",
	"p1" : "Ф"
}, {
	"personal_username" : "Пірожок  Л.І.",
	"personal_surname" : "Пірожок ",
	"personal_name" : "Ларіса ",
	"personal_patronymic" : "Іванівна ",
	"personal_id" : 2650,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 16,
	"department_name" : "Офтальмологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PirozhokLI",
	"p1" : "П"
}, {
	"personal_username" : "Пірожок Л.І.",
	"personal_surname" : "Пірожок",
	"personal_name" : "Лариса",
	"personal_patronymic" : "Іванівна",
	"personal_id" : 279,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 16,
	"department_name" : "Офтальмологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PirozhokLI",
	"p1" : "П"
}, {
	"personal_username" : "Івахов П.Ю.",
	"personal_surname" : "Івахов",
	"personal_name" : "Павло",
	"personal_patronymic" : "Юрійович",
	"personal_id" : 148,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 19,
	"department_name" : "Приймальне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "IvakhovPYu",
	"p1" : "І"
}, {
	"personal_username" : "Михайленко Ю.О.",
	"personal_surname" : "Михайленко",
	"personal_name" : "Юлія",
	"personal_patronymic" : "Олександрівна",
	"personal_id" : 149,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 19,
	"department_name" : "Приймальне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MikhajlenkoYuO",
	"p1" : "М"
}, {
	"personal_username" : "Кушнір І.А.",
	"personal_surname" : "Кушнір",
	"personal_name" : "Іванна",
	"personal_patronymic" : "Анатоліївна",
	"personal_id" : 150,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 19,
	"department_name" : "Приймальне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KushnirIA",
	"p1" : "К"
}, {
	"personal_username" : "Доценко О.А.",
	"personal_surname" : "Доценко",
	"personal_name" : "Оксана",
	"personal_patronymic" : "Анатоліївна",
	"personal_id" : 205,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 19,
	"department_name" : "Приймальне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "DotsenkoOA",
	"p1" : "Д"
}, {
	"personal_username" : "Галушко В.М.",
	"personal_surname" : "Галушко",
	"personal_name" : "Василь",
	"personal_patronymic" : "Миколайович",
	"personal_id" : 277,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 20,
	"department_name" : "Проктологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "HalushkoVM",
	"p1" : "Г"
}, {
	"personal_username" : "Керничний В.В.",
	"personal_surname" : "Керничний",
	"personal_name" : "Віталій",
	"personal_patronymic" : "Володимирович",
	"personal_id" : 284,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 20,
	"department_name" : "Проктологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KernichnijVV",
	"p1" : "К"
}, {
	"personal_username" : "Янчук М.А.",
	"personal_surname" : "Янчук",
	"personal_name" : "Микола",
	"personal_patronymic" : "Андрійович",
	"personal_id" : 282,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 20,
	"department_name" : "Проктологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "YanchukMA",
	"p1" : "Я"
}, {
	"personal_username" : "Пискливець М.В.",
	"personal_surname" : "Пискливець",
	"personal_name" : "Марія",
	"personal_patronymic" : "Віталіївна",
	"personal_id" : 152,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 21,
	"department_name" : "Пульмонологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PisklivetsMV",
	"p1" : "П"
}, {
	"personal_username" : "Решетова Л.Д.",
	"personal_surname" : "Решетова",
	"personal_name" : "Людмила",
	"personal_patronymic" : "Денисівна",
	"personal_id" : 153,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 21,
	"department_name" : "Пульмонологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ReshetovaLD",
	"p1" : "Р"
}, {
	"personal_username" : "Ігнатова Л.Б.",
	"personal_surname" : "Ігнатова",
	"personal_name" : "Людмила",
	"personal_patronymic" : "Борисівна",
	"personal_id" : 2698,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 21,
	"department_name" : "Пульмонологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "IhnatovaLB",
	"p1" : "І"
}, {
	"personal_username" : "Онишко В.В.",
	"personal_surname" : "Онишко",
	"personal_name" : "Віктор",
	"personal_patronymic" : "Волдимирович",
	"personal_id" : 2699,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 21,
	"department_name" : "Пульмонологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "OnishkoVV",
	"p1" : "О"
}, {
	"personal_username" : "Білякова Л.А.",
	"personal_surname" : "Білякова",
	"personal_name" : "Лідія",
	"personal_patronymic" : "Андріївна",
	"personal_id" : 154,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 21,
	"department_name" : "Пульмонологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "BilyakovaLA",
	"p1" : "Б"
}, {
	"personal_username" : "Бесараба М.Д.",
	"personal_surname" : "Бесараба",
	"personal_name" : "Микола",
	"personal_patronymic" : "Дмитрович",
	"personal_id" : 156,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 2,
	"position_name" : "Головний позаштатний анестезіолог ДОЗ ХОДА"
	,"position_name2" : "Лікар"
	,"titles":["Лікар вищої категорії"
		]
	,"personal_url" : "BesarabaMD",
	"p1" : "Б"
}, {
	"personal_username" : "Каритун В.В.",
	"personal_surname" : "Каритун",
	"personal_name" : "Володимир",
	"personal_patronymic" : "Володимирович",
	"personal_id" : 158,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KaritunVV",
	"p1" : "К"
}, {
	"personal_username" : "Тоцький С.М.",
	"personal_surname" : "Тоцький",
	"personal_name" : "Сергій",
	"personal_patronymic" : "Миколайович",
	"personal_id" : 159,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "TotskijSM",
	"p1" : "Т"
}, {
	"personal_username" : "Романовський В.П.",
	"personal_surname" : "Романовський",
	"personal_name" : "Віктор",
	"personal_patronymic" : "Петрович",
	"personal_id" : 160,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "RomanovskijVP",
	"p1" : "Р"
}, {
	"personal_username" : "Погурало П.А.",
	"personal_surname" : "Погурало",
	"personal_name" : "Петро",
	"personal_patronymic" : "Адріянович",
	"personal_id" : 161,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PohuraloPA",
	"p1" : "П"
}, {
	"personal_username" : "Бахмацький І.Ф.",
	"personal_surname" : "Бахмацький",
	"personal_name" : "Ігор",
	"personal_patronymic" : "Феофанович",
	"personal_id" : 162,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "BakhmatskijIF",
	"p1" : "Б"
}, {
	"personal_username" : "Загоруйко В.К.",
	"personal_surname" : "Загоруйко",
	"personal_name" : "Валентин",
	"personal_patronymic" : "Кузьмич",
	"personal_id" : 163,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ZahorujkoVK",
	"p1" : "З"
}, {
	"personal_username" : "Бойчук П.А.",
	"personal_surname" : "Бойчук",
	"personal_name" : "Павло",
	"personal_patronymic" : "Анатолійович",
	"personal_id" : 164,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "BojchukPA",
	"p1" : "Б"
}, {
	"personal_username" : "Цехмістер К.Ю.",
	"personal_surname" : "Цехмістер",
	"personal_name" : "Катерина",
	"personal_patronymic" : "Юріївна",
	"personal_id" : 167,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "TsekhmisterKYu",
	"p1" : "Ц"
}, {
	"personal_username" : "Ніколенко П.Є.",
	"personal_surname" : "Ніколенко",
	"personal_name" : "Петро",
	"personal_patronymic" : "Євгенович",
	"personal_id" : 168,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "NikolenkoPYe",
	"p1" : "Н"
}, {
	"personal_username" : "Машевський М.Й.",
	"personal_surname" : "Машевський",
	"personal_name" : "Микола",
	"personal_patronymic" : "Йосипович",
	"personal_id" : 169,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MashevskijMJ",
	"p1" : "М"
}, {
	"personal_username" : "Урсол Н.Б.",
	"personal_surname" : "Урсол",
	"personal_name" : "Наталія",
	"personal_patronymic" : "Борисівна",
	"personal_id" : 124,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 1,
	"department_name" : "Алергологiчне",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "UrsolNB",
	"p1" : "У"
}, {
	"personal_username" : "Корандо Н.В.",
	"personal_surname" : "Корандо",
	"personal_name" : "Наталія",
	"personal_patronymic" : "Вікторівна",
	"personal_id" : 2667,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 2,
	"department_name" : "Гінекологічне",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "KorandoNV",
	"p1" : "К"
}, {
	"personal_username" : "Дунець О.Д.",
	"personal_surname" : "Дунець",
	"personal_name" : "Орися",
	"personal_patronymic" : "Дмитрівна",
	"personal_id" : 129,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 3,
	"department_name" : "Гастроентерологічне",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "DunetsOD",
	"p1" : "Д"
}, {
	"personal_username" : "Рехтман Г.Б.",
	"personal_surname" : "Рехтман",
	"personal_name" : "Георгій",
	"personal_patronymic" : "Борисович",
	"personal_id" : 2669,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 4,
	"department_name" : "Гематологічне",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "RekhtmanHB",
	"p1" : "Р"
}, {
	"personal_username" : "Одолінський С.С.",
	"personal_surname" : "Одолінський",
	"personal_name" : "Сергій",
	"personal_patronymic" : "Сергійович",
	"personal_id" : 175,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 5,
	"department_name" : "Детоксикації",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "OdolinskijSeS",
	"p1" : "О"
}, {
	"personal_username" : "Карнаух К.В.",
	"personal_surname" : "Карнаух",
	"personal_name" : "Костянтин",
	"personal_patronymic" : "Володимирович",
	"personal_id" : 166,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 6,
	"department_name" : "ЕГ реанімація доросла",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення"
	,"titles":["Лікар вищої категорії"
		]
	,"personal_url" : "KarnaukhKV",
	"p1" : "К"
}, {
	"personal_username" : "Притуляк Л.В.",
	"personal_surname" : "Притуляк",
	"personal_name" : "Лариса",
	"personal_patronymic" : "Вікторівна",
	"personal_id" : 123,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 7,
	"department_name" : "ЕГПВ та Н",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "PritulyakLV",
	"p1" : "П"
}, {
	"personal_username" : "Мукомела Л.І.",
	"personal_surname" : "Мукомела",
	"personal_name" : "Людмила",
	"personal_patronymic" : "Іванівна",
	"personal_id" : 2689,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 8,
	"department_name" : "Ендокринологія",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "MukomelaLI",
	"p1" : "М"
}, {
	"personal_username" : "Кланца А.І.",
	"personal_surname" : "Кланца",
	"personal_name" : "Андрій",
	"personal_patronymic" : "Іванович",
	"personal_id" : 264,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 9,
	"department_name" : "Кардіохірургічне",
	"department_name2" : "Кардіореанімація",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "KlantsaAI",
	"p1" : "К"
}, {
	"personal_username" : "Костюк О.В.",
	"personal_surname" : "Костюк",
	"personal_name" : "Олександр",
	"personal_patronymic" : "Володимирович",
	"personal_id" : 294,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 11,
	"department_name" : "Неврологічне",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "KostyukOV",
	"p1" : "К"
}, {
	"personal_username" : "Левицький В.М.",
	"personal_surname" : "Левицький",
	"personal_name" : "Василь",
	"personal_patronymic" : "Михайлович",
	"personal_id" : 230,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 12,
	"department_name" : "Нейрохірургічне",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "LevitskijVM",
	"p1" : "Л"
}, {
	"personal_username" : "Щербіна Н.В.",
	"personal_surname" : "Щербіна",
	"personal_name" : "Наталія",
	"personal_patronymic" : "Володимирівна",
	"personal_id" : 134,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 13,
	"department_name" : "Нефрологічне",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "ShcherbinaNV",
	"p1" : "Щ"
}, {
	"personal_username" : "Гринчук О.П.",
	"personal_surname" : "Гринчук",
	"personal_name" : "Олександр",
	"personal_patronymic" : "Петрович",
	"personal_id" : 249,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 14,
	"department_name" : "Опікове",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "HrinchukOP",
	"p1" : "Г"
}, {
	"personal_username" : "Павлішен Ю.І.",
	"personal_surname" : "Павлішен",
	"personal_name" : "Юрій",
	"personal_patronymic" : "Іванович",
	"personal_id" : 252,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 15,
	"department_name" : "Ортопедичне",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "PavlishenYuI",
	"p1" : "П"
}, {
	"personal_username" : "Чернецький В.С.",
	"personal_surname" : "Чернецький",
	"personal_name" : "Віталій",
	"personal_patronymic" : "Северинович",
	"personal_id" : 285,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 16,
	"department_name" : "Офтальмологічне",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "ChernetskijVS",
	"p1" : "Ч"
}, {
	"personal_username" : "Довгань Л.І.",
	"personal_surname" : "Довгань",
	"personal_name" : "Лариса",
	"personal_patronymic" : "Іванівна",
	"personal_id" : 146,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 19,
	"department_name" : "Приймальне",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "DovhanLI",
	"p1" : "Д"
}, {
	"personal_username" : "Балицький В.В.",
	"personal_surname" : "Балицький",
	"personal_name" : "Віталій",
	"personal_patronymic" : "Вікторович",
	"personal_id" : 280,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 20,
	"department_name" : "Проктологічне",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "BalitskijVV",
	"p1" : "Б"
}, {
	"personal_username" : "Алешко А.П.",
	"personal_surname" : "Алешко",
	"personal_name" : "Анатолій",
	"personal_patronymic" : "Петрович",
	"personal_id" : 151,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 21,
	"department_name" : "Пульмонологічне",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення"
	,"titles":["к.м.н."
		,"вища категорія"
		,"заслужений лікар України"
		,"1955 р.н."
		]
	,"personal_url" : "AleshkoAP",
	"p1" : "А"
}, {
	"personal_username" : "Логвін О.О.",
	"personal_surname" : "Логвін",
	"personal_name" : "Олена",
	"personal_patronymic" : "Олександрівна",
	"personal_id" : 247,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 19,
	"department_name" : "Приймальне",
	"position_id" : 4,
	"position_name" : "Середній мед. персонал",
	"personal_url" : "LohvinOO",
	"p1" : "Л"
}, {
	"personal_username" : "Новосядла І.М.",
	"personal_surname" : "Новосядла",
	"personal_name" : "Ірина",
	"personal_patronymic" : "Миколаївна",
	"personal_id" : 229,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 19,
	"department_name" : "Приймальне",
	"position_id" : 6,
	"position_name" : "Оператор",
	"personal_url" : "NovosyadlaIM",
	"p1" : "Н"
}, {
	"personal_username" : "Приймальне",
	"personal_surname" : "Приймальне",
	"personal_name" : "7",
	"personal_patronymic" : "к",
	"personal_id" : 248,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 19,
	"department_name" : "Приймальне",
	"position_id" : 6,
	"position_name" : "Оператор",
	"personal_url" : "Prijmalne",
	"p1" : "П"
}, {
	"personal_username" : "Загоруйко В.В.",
	"personal_surname" : "Загоруйко",
	"personal_name" : "Володимир",
	"personal_patronymic" : "Валентинович",
	"personal_id" : 170,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ZahorujkoVV",
	"p1" : "З"
}, {
	"personal_username" : "Маркова В.М.",
	"personal_surname" : "Маркова",
	"personal_name" : "Вікторія",
	"personal_patronymic" : "Михайлівна",
	"personal_id" : 171,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MarkovaVM",
	"p1" : "М"
}, {
	"personal_username" : "Крушельницький С.В.",
	"personal_surname" : "Крушельницький",
	"personal_name" : "Сергій",
	"personal_patronymic" : "Віталійович",
	"personal_id" : 172,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KrushelnitskijSV",
	"p1" : "К"
}, {
	"personal_username" : "Кирик Р.В.",
	"personal_surname" : "Кирик",
	"personal_name" : "Роман",
	"personal_patronymic" : "Володимирович",
	"personal_id" : 173,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KirikRV",
	"p1" : "К"
}, {
	"personal_username" : "Мельник А.В.",
	"personal_surname" : "Мельник",
	"personal_name" : "Андрій",
	"personal_patronymic" : "Віталійович",
	"personal_id" : 174,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MelnikAV",
	"p1" : "М"
}, {
	"personal_username" : "Дема О.І.",
	"personal_surname" : "Дема",
	"personal_name" : "Олександр",
	"personal_patronymic" : "Іванович",
	"personal_id" : 184,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "DemaOI",
	"p1" : "Д"
}, {
	"personal_username" : "Вакулено В.О.",
	"personal_surname" : "Вакулено",
	"personal_name" : "Василь",
	"personal_patronymic" : "Олександрович",
	"personal_id" : 192,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "VakulenoVO",
	"p1" : "В"
}, {
	"personal_username" : "Лиса Л.В.",
	"personal_surname" : "Лиса",
	"personal_name" : "Леся",
	"personal_patronymic" : "Володимирівна",
	"personal_id" : 195,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "LisaLV",
	"p1" : "Л"
}, {
	"personal_username" : "Андрухова Н.П.",
	"personal_surname" : "Андрухова",
	"personal_name" : "Неоніла",
	"personal_patronymic" : "Петрівна",
	"personal_id" : 199,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "AndrukhovaNP",
	"p1" : "А"
}, {
	"personal_username" : "Каритун(мол) В.В.",
	"personal_surname" : "Каритун(мол)",
	"personal_name" : "Володимир",
	"personal_patronymic" : "Володимирович",
	"personal_id" : 246,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "Karitun(mol)VV",
	"p1" : "К"
}, {
	"personal_username" : "Кирик  Р.В.",
	"personal_surname" : "Кирик ",
	"personal_name" : "Роман",
	"personal_patronymic" : "Володимирович",
	"personal_id" : 308,
	"personal_surgeon" : false,
	"personal_anesthetist" : true,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KirikRV",
	"p1" : "К"
}, {
	"personal_username" : "Криньов К.Ю.",
	"personal_surname" : "Криньов",
	"personal_name" : "Костянтин",
	"personal_patronymic" : "Юрійович",
	"personal_id" : 319,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 22,
	"department_name" : "Реанімаційне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KrinovKYu",
	"p1" : "К"
}, {
	"personal_username" : "Борисенко І.Д.",
	"personal_surname" : "Борисенко",
	"personal_name" : "Ірена",
	"personal_patronymic" : "Дмитрівна",
	"personal_id" : 125,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 23,
	"department_name" : "Ревматологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "BorisenkoID",
	"p1" : "Б"
}, {
	"personal_username" : "Закревська В.О.",
	"personal_surname" : "Закревська",
	"personal_name" : "Валентина",
	"personal_patronymic" : "Олексіїівна",
	"personal_id" : 126,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 23,
	"department_name" : "Ревматологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ZakrevskaVO",
	"p1" : "З"
}, {
	"personal_username" : "Шалавінська А.М.",
	"personal_surname" : "Шалавінська",
	"personal_name" : "Анна",
	"personal_patronymic" : "Михайлівна",
	"personal_id" : 128,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 23,
	"department_name" : "Ревматологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ShalavinskaAM",
	"p1" : "Ш"
}, {
	"personal_username" : "Тарасюк М.І.",
	"personal_surname" : "Тарасюк",
	"personal_name" : "Марина",
	"personal_patronymic" : "Ігорівна",
	"personal_id" : 127,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 23,
	"department_name" : "Ревматологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "TarasyukMI",
	"p1" : "Т"
}, {
	"personal_username" : "Лящук І.А.",
	"personal_surname" : "Лящук",
	"personal_name" : "Іванна",
	"personal_patronymic" : "Анатоліівна",
	"personal_id" : 2712,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 23,
	"department_name" : "Ревматологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "LyashchukIA",
	"p1" : "Л"
}, {
	"personal_username" : "Пискливець З.С.",
	"personal_surname" : "Пискливець",
	"personal_name" : "Зорян",
	"personal_patronymic" : "Степанович",
	"personal_id" : 240,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 24,
	"department_name" : "Судинної хірургії",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PisklivetsZS",
	"p1" : "П"
}, {
	"personal_username" : "Решетов Л.М.",
	"personal_surname" : "Решетов",
	"personal_name" : "Леонід",
	"personal_patronymic" : "Михайлович",
	"personal_id" : 241,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 24,
	"department_name" : "Судинної хірургії",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ReshetovLM",
	"p1" : "Р"
}, {
	"personal_username" : "Мартинюк В.Г.",
	"personal_surname" : "Мартинюк",
	"personal_name" : "Вадим",
	"personal_patronymic" : "Григорович",
	"personal_id" : 242,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 24,
	"department_name" : "Судинної хірургії",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MartinyukVH",
	"p1" : "М"
}, {
	"personal_username" : "Авраменко В.С.",
	"personal_surname" : "Авраменко",
	"personal_name" : "Владислав",
	"personal_patronymic" : "Сергійович",
	"personal_id" : 243,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 24,
	"department_name" : "Судинної хірургії",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "AvramenkoVS",
	"p1" : "А"
}, {
	"personal_username" : "Решетов Ю.Л.",
	"personal_surname" : "Решетов",
	"personal_name" : "Юрій",
	"personal_patronymic" : "Леонідович",
	"personal_id" : 244,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 24,
	"department_name" : "Судинної хірургії",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ReshetovYuL",
	"p1" : "Р"
}, {
	"personal_username" : "Прелепа О.І.",
	"personal_surname" : "Прелепа",
	"personal_name" : "Олексій",
	"personal_patronymic" : "Іванович",
	"personal_id" : 2653,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 25,
	"department_name" : "Торакальної хірургії",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PrelepaOI",
	"p1" : "П"
}, {
	"personal_username" : "Стрілець П.А.",
	"personal_surname" : "Стрілець",
	"personal_name" : "Петро",
	"personal_patronymic" : "Антонович",
	"personal_id" : 2654,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 25,
	"department_name" : "Торакальної хірургії",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "StriletsPA",
	"p1" : "С"
}, {
	"personal_username" : "Васильківський В.В.",
	"personal_surname" : "Васильківський",
	"personal_name" : "Віталій",
	"personal_patronymic" : "Вікторович",
	"personal_id" : 2655,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 25,
	"department_name" : "Торакальної хірургії",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "VasilkivskijVV",
	"p1" : "В"
}, {
	"personal_username" : "Прилепа О.І.",
	"personal_surname" : "Прилепа",
	"personal_name" : "Олексій",
	"personal_patronymic" : "Іванович",
	"personal_id" : 2659,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 25,
	"department_name" : "Торакальної хірургії",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PrilepaOI",
	"p1" : "П"
}, {
	"personal_username" : "Корнійчук Ю.О.",
	"personal_surname" : "Корнійчук",
	"personal_name" : "Юрій",
	"personal_patronymic" : "Олексійович",
	"personal_id" : 2660,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 25,
	"department_name" : "Торакальної хірургії",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KornijchukYuO",
	"p1" : "К"
}, {
	"personal_username" : "Калиновський В.В.",
	"personal_surname" : "Калиновський",
	"personal_name" : "В’ячеслав",
	"personal_patronymic" : "Валерійович",
	"personal_id" : 227,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 25,
	"department_name" : "Торакальної хірургії",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KalinovskijVV",
	"p1" : "К"
}, {
	"personal_username" : "Чубар І.В.",
	"personal_surname" : "Чубар",
	"personal_name" : "Іван",
	"personal_patronymic" : "Вікторович",
	"personal_id" : 2716,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 25,
	"department_name" : "Торакальної хірургії",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "ChubarIV",
	"p1" : "Ч"
}, {
	"personal_username" : "Підмурняк Ол.О.",
	"personal_surname" : "Підмурняк",
	"personal_name" : "Олексій",
	"personal_patronymic" : "Олексійович",
	"personal_id" : 118,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 26,
	"department_name" : "Урологічне",
	"position_id" : 2,
	"position_name" : "Заступник головного лікаря з хірургічної роботи",
	"position_name2" : "Лікар"
	,"titles":[
	"кандидат медичних наук"
	,"дійсний член Європейської асоціації урологів"
		]
	,"personal_url" : "PidmurnyakOlO",
	"p1" : "П"
}, {
	"personal_username" : "Дрогоруб А.А.",
	"personal_surname" : "Дрогоруб",
	"personal_name" : "Андрій",
	"personal_patronymic" : "Анатолійович",
	"personal_id" : 122,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 26,
	"department_name" : "Урологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "DrohorubAA",
	"p1" : "Д"
}, {
	"personal_username" : "Бодько О.Є.",
	"personal_surname" : "Бодько",
	"personal_name" : "Олександр",
	"personal_patronymic" : "Євгенійович",
	"personal_id" : 207,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 26,
	"department_name" : "Урологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "BodkoOYe",
	"p1" : "Б"
}, {
	"personal_username" : "Яткевич Ю.В.",
	"personal_surname" : "Яткевич",
	"personal_name" : "Юрій",
	"personal_patronymic" : "Васильович",
	"personal_id" : 208,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 26,
	"department_name" : "Урологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "YatkevichYuV",
	"p1" : "Я"
}, {
	"personal_username" : "Войцешин В.В.",
	"personal_surname" : "Войцешин",
	"personal_name" : "Володимир",
	"personal_patronymic" : "Васильович",
	"personal_id" : 209,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 26,
	"department_name" : "Урологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "VojtseshinVV",
	"p1" : "В"
}, {
	"personal_username" : "Монастирський В.М.",
	"personal_surname" : "Монастирський",
	"personal_name" : "Володимир",
	"personal_patronymic" : "Миколайович",
	"personal_id" : 210,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 26,
	"department_name" : "Урологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MonastirskijVM",
	"p1" : "М"
}, {
	"personal_username" : "Алешко О.А.",
	"personal_surname" : "Алешко",
	"personal_name" : "Олександр",
	"personal_patronymic" : "Анатолійович",
	"personal_id" : 211,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 26,
	"department_name" : "Урологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "AleshkoOA",
	"p1" : "А"
}, {
	"personal_username" : "Добровольський В.А.",
	"personal_surname" : "Добровольський",
	"personal_name" : "Вадим",
	"personal_patronymic" : "Анатолійович",
	"personal_id" : 212,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 26,
	"department_name" : "Урологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "DobrovolskijVA",
	"p1" : "Д"
}, {
	"personal_username" : "Боюк В.В.",
	"personal_surname" : "Боюк",
	"personal_name" : "Віктор",
	"personal_patronymic" : "Васильович",
	"personal_id" : 213,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 26,
	"department_name" : "Урологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "BoyukVV",
	"p1" : "Б"
}, {
	"personal_username" : "Собчинський К.С.",
	"personal_surname" : "Собчинський",
	"personal_name" : "Костянтин",
	"personal_patronymic" : "Станіславович",
	"personal_id" : 214,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 26,
	"department_name" : "Урологічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "SobchinskijKS",
	"p1" : "С"
}, {
	"personal_username" : "Власов В.В.",
	"personal_surname" : "Власов",
	"personal_name" : "Василь",
	"personal_patronymic" : "Володимирович",
	"personal_id" : 217,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "VlasovVV",
	"p1" : "В"
}, {
	"personal_username" : "Подопригора Ю.А.",
	"personal_surname" : "Подопригора",
	"personal_name" : "Юрій",
	"personal_patronymic" : "Анатолійович",
	"personal_id" : 218,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PodoprihoraYuA",
	"p1" : "П"
}, {
	"personal_username" : "Латинський Е.В.",
	"personal_surname" : "Латинський",
	"personal_name" : "Едуард",
	"personal_patronymic" : "Владиславович",
	"personal_id" : 219,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "LatinskijEV",
	"p1" : "Л"
}, {
	"personal_username" : "Тропарчук О.І.",
	"personal_surname" : "Тропарчук",
	"personal_name" : "Олег",
	"personal_patronymic" : "Іванович",
	"personal_id" : 220,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "TroparchukOI",
	"p1" : "Т"
}, {
	"personal_username" : "Приступа М.Є.",
	"personal_surname" : "Приступа",
	"personal_name" : "Микола",
	"personal_patronymic" : "Євгенійович",
	"personal_id" : 221,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PristupaMYe",
	"p1" : "П"
}, {
	"personal_username" : "Британчук Р.В.",
	"personal_surname" : "Британчук",
	"personal_name" : "Ростислав",
	"personal_patronymic" : "Васильович",
	"personal_id" : 222,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "BritanchukRV",
	"p1" : "Б"
}, {
	"personal_username" : "Петерчук О.Ф.",
	"personal_surname" : "Петерчук",
	"personal_name" : "Олег",
	"personal_patronymic" : "Федорович",
	"personal_id" : 223,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PeterchukOF",
	"p1" : "П"
}, {
	"personal_username" : "Сапожнік А.П.",
	"personal_surname" : "Сапожнік",
	"personal_name" : "Андрій",
	"personal_patronymic" : "Павлович",
	"personal_id" : 224,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "SapozhnikAP",
	"p1" : "С"
}, {
	"personal_username" : "Полоневич С.В.",
	"personal_surname" : "Полоневич",
	"personal_name" : "Сергій",
	"personal_patronymic" : "Васильович",
	"personal_id" : 225,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PolonevichSV",
	"p1" : "П"
}, {
	"personal_username" : "Костюк О.О.",
	"personal_surname" : "Костюк",
	"personal_name" : "Олександр",
	"personal_patronymic" : "Олександрович",
	"personal_id" : 226,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KostyukOO",
	"p1" : "К"
}, {
	"personal_username" : "Калиновський В.В.",
	"personal_surname" : "Калиновський",
	"personal_name" : "В’ячеслав",
	"personal_patronymic" : "Валерійович",
	"personal_id" : 227,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KalinovskijVV",
	"p1" : "К"
}, {
	"personal_username" : "Бабій І.В.",
	"personal_surname" : "Бабій",
	"personal_name" : "Ігор",
	"personal_patronymic" : "Володимирович",
	"personal_id" : 228,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "BabijIV",
	"p1" : "Б"
}, {
	"personal_username" : "Козак І.О.",
	"personal_surname" : "Козак",
	"personal_name" : "Іван",
	"personal_patronymic" : "Олександрович",
	"personal_id" : 261,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "KozakIO",
	"p1" : "К"
}, {
	"personal_username" : "Міщенко Ф.П.",
	"personal_surname" : "Міщенко",
	"personal_name" : "Федір",
	"personal_patronymic" : "Пилипович",
	"personal_id" : 262,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MishchenkoFP",
	"p1" : "М"
}, {
	"personal_username" : "Суходоля А.І.",
	"personal_surname" : "Суходоля",
	"personal_name" : "Анатолій",
	"personal_patronymic" : "Іванович",
	"personal_id" : 263,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 2,
	"position_name" : "Головний хірург Хмельницької області",
	"position_name2" : "Лікар"
	,"titles":[
		"Доктор медичних наук"
		,"Професор"
		,"Завідуючий кафедрою хірургії післядипломної освіти"
		,"Заслужений лікар України"
	]
	,"personal_url" : "SukhodolyaAI",
	"p1" : "С"
}, {
	"personal_username" : "Павлюк В.Б.",
	"personal_surname" : "Павлюк",
	"personal_name" : "Василь",
	"personal_patronymic" : "Богданович",
	"personal_id" : 307,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "PavlyukVB",
	"p1" : "П"
}, {
	"personal_username" : "Микитюк С.Р.",
	"personal_surname" : "Микитюк",
	"personal_name" : "Святослав",
	"personal_patronymic" : "Ростиславович",
	"personal_id" : 2663,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "MikityukSR",
	"p1" : "М"
}, {
	"personal_username" : "Суходоля С.А.",
	"personal_surname" : "Суходоля",
	"personal_name" : "Сергій",
	"personal_patronymic" : "Анатолійович",
	"personal_id" : 2715,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "SukhodolyaSA",
	"p1" : "С"
}, {
	"personal_username" : "Фелонюк Р.В.",
	"personal_surname" : "Фелонюк",
	"personal_name" : "Роман",
	"personal_patronymic" : "Васильович",
	"personal_id" : 2643,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 28,
	"department_name" : "Щелепно-лицьової хірургії",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "FelonyukRV",
	"p1" : "Ф"
}, {
	"personal_username" : "Овчарук А.С.",
	"personal_surname" : "Овчарук",
	"personal_name" : "Андрій",
	"personal_patronymic" : "Степанович",
	"personal_id" : 2644,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 28,
	"department_name" : "Щелепно-лицьової хірургії",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "OvcharukAS",
	"p1" : "О"
}, {
	"personal_username" : "Нагорний І.М.",
	"personal_surname" : "Нагорний",
	"personal_name" : "Іван",
	"personal_patronymic" : "Михайлович",
	"personal_id" : 2645,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 28,
	"department_name" : "Щелепно-лицьової хірургії",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "NahornijIM",
	"p1" : "Н"
}, {
	"personal_username" : "Ренген р.р.",
	"personal_surname" : "Ренген",
	"personal_name" : "Ренген",
	"personal_patronymic" : "Ренген",
	"personal_id" : 2714,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 29,
	"department_name" : "Поліклініка",
	"position_id" : 1,
	"position_name" : "Лікар",
	"personal_url" : "Renhenrr",
	"p1" : "Р"
}, {
	"personal_username" : "Урсол Н.Б.",
	"personal_surname" : "Урсол",
	"personal_name" : "Наталія",
	"personal_patronymic" : "Борисівна",
	"personal_id" : 124,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 23,
	"department_name" : "Ревматологічне",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "UrsolNB",
	"p1" : "У"
}, {
	"personal_username" : "Міщенко Є.М.",
	"personal_surname" : "Міщенко",
	"personal_name" : "Євген",
	"personal_patronymic" : "Миколайович",
	"personal_id" : 239,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 24,
	"department_name" : "Судинної хірургії",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "MishchenkoYeM",
	"p1" : "М"
}, {
	"personal_username" : "Франковський Р.Б.",
	"personal_surname" : "Франковський",
	"personal_name" : "Раймонд",
	"personal_patronymic" : "Болеславович",
	"personal_id" : 2658,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 25,
	"department_name" : "Торакальної хірургії",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "FrankovskijRB",
	"p1" : "Ф"
}, {
	"personal_username" : "Собчинський С.А.",
	"personal_surname" : "Собчинський",
	"personal_name" : "Станіслав",
	"personal_patronymic" : "Антонович",
	"personal_id" : 155,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 26,
	"department_name" : "Урологічне",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "SobchinskijSA",
	"p1" : "С"
}, {
	"personal_username" : "Підмурняк Ор.О.",
	"personal_surname" : "Підмурняк",
	"personal_name" : "Олександр",
	"personal_patronymic" : "Олексійович",
	"personal_id" : 216,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 27,
	"department_name" : "Хірургічне",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення"
	,"titles":["доктор медичних наук"
	]
	,"personal_url" : "PidmurnyakOrO",
	"p1" : "П"
}, {
	"personal_username" : "Компанієць Г.П.",
	"personal_surname" : "Компанієць",
	"personal_name" : "Ганна",
	"personal_patronymic" : "Панасівна",
	"personal_id" : 2646,
	"personal_surgeon" : true,
	"personal_anesthetist" : false,
	"department_id" : 28,
	"department_name" : "Щелепно-лицьової хірургії",
	"position_id" : 3,
	"position_name" : "Завідуючий відділення",
	"personal_url" : "KompaniyetsHP",
	"p1" : "К"
}, {
	"personal_username" : "Поліклініка",
	"personal_surname" : "Поліклініка",
	"personal_name" : "7",
	"personal_patronymic" : "к",
	"personal_id" : 276,
	"personal_surgeon" : false,
	"personal_anesthetist" : false,
	"department_id" : 29,
	"department_name" : "Поліклініка",
	"position_id" : 6,
	"position_name" : "Оператор",
	"personal_url" : "Poliklinika",
	"p1" : "П"
	} ]
}
