[ {
  "personal_username" : "Скакальська Л.І.",
  "personal_surname" : "Скакальська",
  "personal_name" : "Людмила",
  "personal_patronymic" : "Іванівна",
  "personal_id" : 2648,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 1,
  "department_name" : "Алергологiчне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Камінська О.Я.",
  "personal_surname" : "Камінська",
  "personal_name" : "Ольга",
  "personal_patronymic" : "Яківна",
  "personal_id" : 2649,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 1,
  "department_name" : "Алергологiчне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Чорнобровий П.М.",
  "personal_surname" : "Чорнобровий",
  "personal_name" : "Павло",
  "personal_patronymic" : "Миколайович",
  "personal_id" : 2692,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 1,
  "department_name" : "Алергологiчне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Флаксемберг М.А.",
  "personal_surname" : "Флаксемберг",
  "personal_name" : "Майя",
  "personal_patronymic" : "Аркадіївна",
  "personal_id" : 2666,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 2,
  "department_name" : "Гінекологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Антонецька Н.Б.",
  "personal_surname" : "Антонецька",
  "personal_name" : "Наталія",
  "personal_patronymic" : "Борисівна",
  "personal_id" : 2668,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 2,
  "department_name" : "Гінекологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Щепкіна Т.М.",
  "personal_surname" : "Щепкіна",
  "personal_name" : "Тамара",
  "personal_patronymic" : "Михалівна",
  "personal_id" : 2674,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 2,
  "department_name" : "Гінекологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Онишко В.Ю.",
  "personal_surname" : "Онишко",
  "personal_name" : "Віктор",
  "personal_patronymic" : "Юхимович",
  "personal_id" : 2694,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 2,
  "department_name" : "Гінекологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Павлюк Т.В.",
  "personal_surname" : "Павлюк",
  "personal_name" : "Тамара",
  "personal_patronymic" : "Вікторівна",
  "personal_id" : 130,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 3,
  "department_name" : "Гастроентерологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Афійчук Л.В.",
  "personal_surname" : "Афійчук",
  "personal_name" : "Людмила",
  "personal_patronymic" : "Василівна",
  "personal_id" : 131,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 3,
  "department_name" : "Гастроентерологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Мацишина Л.В.",
  "personal_surname" : "Мацишина",
  "personal_name" : "Людмила",
  "personal_patronymic" : "Володимирівна",
  "personal_id" : 133,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 3,
  "department_name" : "Гастроентерологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Олешко Л.В.",
  "personal_surname" : "Олешко",
  "personal_name" : "Любов",
  "personal_patronymic" : "Василівна",
  "personal_id" : 2678,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 3,
  "department_name" : "Гастроентерологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кіндзерська А.В.",
  "personal_surname" : "Кіндзерська",
  "personal_name" : "Ала",
  "personal_patronymic" : "Василівна",
  "personal_id" : 2680,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 3,
  "department_name" : "Гастроентерологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Повх В.В.",
  "personal_surname" : "Повх",
  "personal_name" : "Віта",
  "personal_patronymic" : "Володимирівна",
  "personal_id" : 2681,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 3,
  "department_name" : "Гастроентерологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Мацишена Л.Д.",
  "personal_surname" : "Мацишена",
  "personal_name" : "Людмила",
  "personal_patronymic" : "Дмитрівна",
  "personal_id" : 2693,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 3,
  "department_name" : "Гастроентерологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Алешко Л.В.",
  "personal_surname" : "Алешко",
  "personal_name" : "Любов",
  "personal_patronymic" : "Василівна",
  "personal_id" : 132,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 3,
  "department_name" : "Гастроентерологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Бобровник  А.О.",
  "personal_surname" : "Бобровник",
  "personal_name" : "Андрій",
  "personal_patronymic" : "Олександрович",
  "personal_id" : 2670,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 4,
  "department_name" : "Гематологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Підмурняк Н.М.",
  "personal_surname" : "Підмурняк",
  "personal_name" : "Надія",
  "personal_patronymic" : "Миколаївна",
  "personal_id" : 2671,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 4,
  "department_name" : "Гематологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Пещинська Н.С.",
  "personal_surname" : "Пещинська",
  "personal_name" : "Надія",
  "personal_patronymic" : "Сафонівна",
  "personal_id" : 2672,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 4,
  "department_name" : "Гематологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Мороз Л.П.",
  "personal_surname" : "Мороз",
  "personal_name" : "Лариса",
  "personal_patronymic" : "Петрівна",
  "personal_id" : 2673,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 4,
  "department_name" : "Гематологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Бобровник А.О.",
  "personal_surname" : "Бобровник",
  "personal_name" : "Андрій",
  "personal_patronymic" : "Олександрович",
  "personal_id" : 2675,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 4,
  "department_name" : "Гематологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Щепіна Т.М.",
  "personal_surname" : "Щепіна",
  "personal_name" : "Тамара",
  "personal_patronymic" : "Михалівна",
  "personal_id" : 2696,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 4,
  "department_name" : "Гематологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Онуфран В.І.",
  "personal_surname" : "Онуфран",
  "personal_name" : "Віталій",
  "personal_patronymic" : "Іванович",
  "personal_id" : 139,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 5,
  "department_name" : "Детоксикації",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Педосюк Т.О.",
  "personal_surname" : "Педосюк",
  "personal_name" : "Тетяна",
  "personal_patronymic" : "Олександрівна",
  "personal_id" : 140,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 5,
  "department_name" : "Детоксикації",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Жила Н.В.",
  "personal_surname" : "Жила",
  "personal_name" : "Наталія",
  "personal_patronymic" : "Володимирівна",
  "personal_id" : 141,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 5,
  "department_name" : "Детоксикації",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Бондарук О.З.",
  "personal_surname" : "Бондарук",
  "personal_name" : "Ольга",
  "personal_patronymic" : "Зіновіївна",
  "personal_id" : 142,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 5,
  "department_name" : "Детоксикації",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Щербатюк М.І.",
  "personal_surname" : "Щербатюк",
  "personal_name" : "Микола",
  "personal_patronymic" : "Іванович",
  "personal_id" : 143,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 5,
  "department_name" : "Детоксикації",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Волошина І.М.",
  "personal_surname" : "Волошина",
  "personal_name" : "Інна",
  "personal_patronymic" : "Михайлівна",
  "personal_id" : 144,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 5,
  "department_name" : "Детоксикації",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Косташ В.М.",
  "personal_surname" : "Косташ",
  "personal_name" : "Віктор",
  "personal_patronymic" : "Михайлович",
  "personal_id" : 176,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 5,
  "department_name" : "Детоксикації",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Гончарук В.М.",
  "personal_surname" : "Гончарук",
  "personal_name" : "Володимир",
  "personal_patronymic" : "МИхайлович",
  "personal_id" : 177,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 5,
  "department_name" : "Детоксикації",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Середа І.В.",
  "personal_surname" : "Середа",
  "personal_name" : "Ірина",
  "personal_patronymic" : "Василівна",
  "personal_id" : 178,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 5,
  "department_name" : "Детоксикації",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Малоголовка О.А.",
  "personal_surname" : "Малоголовка",
  "personal_name" : "Олександр",
  "personal_patronymic" : "Андрійович",
  "personal_id" : 179,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 5,
  "department_name" : "Детоксикації",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Білобрицький В.Г.",
  "personal_surname" : "Білобрицький",
  "personal_name" : "Віктор",
  "personal_patronymic" : "Григорович",
  "personal_id" : 180,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 5,
  "department_name" : "Детоксикації",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Дмитришин М.А.",
  "personal_surname" : "Дмитришин",
  "personal_name" : "Микола",
  "personal_patronymic" : "Андрійович",
  "personal_id" : 189,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 5,
  "department_name" : "Детоксикації",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кожановська А.В.",
  "personal_surname" : "Кожановська",
  "personal_name" : "Альоша",
  "personal_patronymic" : "Володимирівна",
  "personal_id" : 200,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 5,
  "department_name" : "Детоксикації",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Вакуленко В.О.",
  "personal_surname" : "Вакуленко",
  "personal_name" : "Василь",
  "personal_patronymic" : "Олександрович",
  "personal_id" : 2703,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 5,
  "department_name" : "Детоксикації",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Грач О.І.",
  "personal_surname" : "Грач",
  "personal_name" : "Олександр",
  "personal_patronymic" : "Іванович",
  "personal_id" : 165,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 6,
  "department_name" : "ЕГ реанімація доросла",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Литовка В.О.",
  "personal_surname" : "Литовка",
  "personal_name" : "Вікторія",
  "personal_patronymic" : "Олександрівна",
  "personal_id" : 185,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 6,
  "department_name" : "ЕГ реанімація доросла",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Іванюк С.В.",
  "personal_surname" : "Іванюк",
  "personal_name" : "Світлана",
  "personal_patronymic" : "Володимирівна",
  "personal_id" : 187,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 6,
  "department_name" : "ЕГ реанімація доросла",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Данилюк С.В.",
  "personal_surname" : "Данилюк",
  "personal_name" : "Сергій",
  "personal_patronymic" : "Віталійович",
  "personal_id" : 191,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 6,
  "department_name" : "ЕГ реанімація доросла",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Чолій В.М.",
  "personal_surname" : "Чолій",
  "personal_name" : "Василь",
  "personal_patronymic" : "Михайлович",
  "personal_id" : 201,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 6,
  "department_name" : "ЕГ реанімація доросла",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Осадчий В.В.",
  "personal_surname" : "Осадчий",
  "personal_name" : "Василь",
  "personal_patronymic" : "Васильович",
  "personal_id" : 202,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 6,
  "department_name" : "ЕГ реанімація доросла",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Поліщук І.В.",
  "personal_surname" : "Поліщук",
  "personal_name" : "Інна",
  "personal_patronymic" : "Володимирівна",
  "personal_id" : 203,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 6,
  "department_name" : "ЕГ реанімація доросла",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Паляниця Н.М.",
  "personal_surname" : "Паляниця",
  "personal_name" : "Наталія",
  "personal_patronymic" : "Миколаївна",
  "personal_id" : 204,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 6,
  "department_name" : "ЕГ реанімація доросла",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Мельник Л.І.",
  "personal_surname" : "Мельник",
  "personal_name" : "Людмила",
  "personal_patronymic" : "Іванівна ",
  "personal_id" : 2707,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 6,
  "department_name" : "ЕГ реанімація доросла",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Рубас Л.В.",
  "personal_surname" : "Рубас",
  "personal_name" : "Лариса",
  "personal_patronymic" : "Вікторівна",
  "personal_id" : 145,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 7,
  "department_name" : "ЕГПВ та Н",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Могильницька Л.А.",
  "personal_surname" : "Могильницька",
  "personal_name" : "Лілія",
  "personal_patronymic" : "Анатолівна",
  "personal_id" : 2682,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 8,
  "department_name" : "Ендокринологія",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Путасевич Н.М.",
  "personal_surname" : "Путасевич",
  "personal_name" : "Надія",
  "personal_patronymic" : "Михалівна",
  "personal_id" : 2683,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 8,
  "department_name" : "Ендокринологія",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Філик М.А.",
  "personal_surname" : "Філик",
  "personal_name" : "Майя",
  "personal_patronymic" : "Арсентівна",
  "personal_id" : 2684,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 8,
  "department_name" : "Ендокринологія",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кононенко В.Х.",
  "personal_surname" : "Кононенко",
  "personal_name" : "Володимир",
  "personal_patronymic" : "Харитонович",
  "personal_id" : 2685,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 8,
  "department_name" : "Ендокринологія",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Заярнюк С.С.",
  "personal_surname" : "Заярнюк",
  "personal_name" : "Світлана",
  "personal_patronymic" : "Сергіївна",
  "personal_id" : 2686,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 8,
  "department_name" : "Ендокринологія",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Вольська Т.В.",
  "personal_surname" : "Вольська",
  "personal_name" : "Тетяна",
  "personal_patronymic" : "Василівна",
  "personal_id" : 2687,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 8,
  "department_name" : "Ендокринологія",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кобунько В.М.",
  "personal_surname" : "Кобунько",
  "personal_name" : "Валентина",
  "personal_patronymic" : "Миколаївна",
  "personal_id" : 2688,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 8,
  "department_name" : "Ендокринологія",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кутсевич Н.М.",
  "personal_surname" : "Кутсевич",
  "personal_name" : "Надія",
  "personal_patronymic" : "Михалівна",
  "personal_id" : 2701,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 8,
  "department_name" : "Ендокринологія",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кутасевич Н.М.",
  "personal_surname" : "Кутасевич",
  "personal_name" : "Надія",
  "personal_patronymic" : "Михалівна",
  "personal_id" : 2702,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 8,
  "department_name" : "Ендокринологія",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Сухарєв В.А.",
  "personal_surname" : "Сухарєв",
  "personal_name" : "Валерій",
  "personal_patronymic" : "Анатолійович",
  "personal_id" : 265,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 9,
  "department_name" : "Кардіохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Сич О.О.",
  "personal_surname" : "Сич",
  "personal_name" : "Олексій",
  "personal_patronymic" : "Олександрович",
  "personal_id" : 266,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 9,
  "department_name" : "Кардіохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Шимків А.П.",
  "personal_surname" : "Шимків",
  "personal_name" : "Андрій",
  "personal_patronymic" : "Петрович",
  "personal_id" : 267,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 9,
  "department_name" : "Кардіохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Швець С.В.",
  "personal_surname" : "Швець",
  "personal_name" : "Сергій",
  "personal_patronymic" : "Васильович",
  "personal_id" : 268,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 9,
  "department_name" : "Кардіохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Пискливець З.Ст.",
  "personal_surname" : "Пискливець",
  "personal_name" : "Зорян",
  "personal_patronymic" : "Степанович",
  "personal_id" : 270,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 9,
  "department_name" : "Кардіохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Мазур Л.М.",
  "personal_surname" : "Мазур",
  "personal_name" : "Лариса",
  "personal_patronymic" : "Миколаївна",
  "personal_id" : 271,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 9,
  "department_name" : "Кардіохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Мельник Л.М.",
  "personal_surname" : "Мельник",
  "personal_name" : "Людмила",
  "personal_patronymic" : "Михайлівна",
  "personal_id" : 272,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 9,
  "department_name" : "Кардіохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Киричук О.В.",
  "personal_surname" : "Киричук",
  "personal_name" : "Ольга",
  "personal_patronymic" : "Василівна",
  "personal_id" : 193,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 10,
  "department_name" : "Кардіореанімація",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Тищенко І.С.",
  "personal_surname" : "Тищенко",
  "personal_name" : "Ірена",
  "personal_patronymic" : "Станіславівна",
  "personal_id" : 196,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 10,
  "department_name" : "Кардіореанімація",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Шалавінський М.П.",
  "personal_surname" : "Шалавінський",
  "personal_name" : "Микола",
  "personal_patronymic" : "Петрович",
  "personal_id" : 197,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 10,
  "department_name" : "Кардіореанімація",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Невеличук Т.А.",
  "personal_surname" : "Невеличук",
  "personal_name" : "Тарас",
  "personal_patronymic" : "Анатолійович",
  "personal_id" : 275,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 10,
  "department_name" : "Кардіореанімація",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Терехівська О.В.",
  "personal_surname" : "Терехівська",
  "personal_name" : "Ольга",
  "personal_patronymic" : "Володимирівна",
  "personal_id" : 2665,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 10,
  "department_name" : "Кардіореанімація",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Степанюк Л.В.",
  "personal_surname" : "Степанюк",
  "personal_name" : "Людмила",
  "personal_patronymic" : "Володимирівна",
  "personal_id" : 304,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 11,
  "department_name" : "Неврологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Григор'єва П.В.",
  "personal_surname" : "Григор'єва",
  "personal_name" : "Павліна",
  "personal_patronymic" : "Володимирівна",
  "personal_id" : 303,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 11,
  "department_name" : "Неврологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кравчук В.О.",
  "personal_surname" : "Кравчук",
  "personal_name" : "Вікторія",
  "personal_patronymic" : "Олександрівна",
  "personal_id" : 305,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 11,
  "department_name" : "Неврологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Гавловський В.К.",
  "personal_surname" : "Гавловський",
  "personal_name" : "Вадим",
  "personal_patronymic" : "Казимирович",
  "personal_id" : 302,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 11,
  "department_name" : "Неврологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Євдохович З.В.",
  "personal_surname" : "Євдохович",
  "personal_name" : "Зоряна",
  "personal_patronymic" : "Володимирівна",
  "personal_id" : 297,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 11,
  "department_name" : "Неврологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Білоус Г.А.",
  "personal_surname" : "Білоус",
  "personal_name" : "Генадій",
  "personal_patronymic" : "Андрійович",
  "personal_id" : 295,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 11,
  "department_name" : "Неврологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Ковтун О.П.",
  "personal_surname" : "Ковтун",
  "personal_name" : "Оксана",
  "personal_patronymic" : "Петрівна",
  "personal_id" : 296,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 11,
  "department_name" : "Неврологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Верхола І.В.",
  "personal_surname" : "Верхола",
  "personal_name" : "Ірина",
  "personal_patronymic" : "Василівна",
  "personal_id" : 298,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 11,
  "department_name" : "Неврологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Бальжик Т.Л.",
  "personal_surname" : "Бальжик",
  "personal_name" : "Тетяна",
  "personal_patronymic" : "Леонідівна",
  "personal_id" : 299,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 11,
  "department_name" : "Неврологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Омелянчук А.Г.",
  "personal_surname" : "Омелянчук",
  "personal_name" : "Анатолій",
  "personal_patronymic" : "Георгійович",
  "personal_id" : 300,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 11,
  "department_name" : "Неврологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Лісова Н.Я.",
  "personal_surname" : "Лісова",
  "personal_name" : "Надія",
  "personal_patronymic" : "Яківна",
  "personal_id" : 301,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 11,
  "department_name" : "Неврологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Літучий В.М.",
  "personal_surname" : "Літучий",
  "personal_name" : "Віталій",
  "personal_patronymic" : "Мусійович",
  "personal_id" : 231,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 12,
  "department_name" : "Нейрохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Тарнович Ю.М.",
  "personal_surname" : "Тарнович",
  "personal_name" : "Юрій",
  "personal_patronymic" : "Миронович",
  "personal_id" : 232,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 12,
  "department_name" : "Нейрохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Ткач Б.В.",
  "personal_surname" : "Ткач",
  "personal_name" : "Борис",
  "personal_patronymic" : "Васильович",
  "personal_id" : 233,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 12,
  "department_name" : "Нейрохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Сарнацький В.В.",
  "personal_surname" : "Сарнацький",
  "personal_name" : "Вадим",
  "personal_patronymic" : "Вадимович",
  "personal_id" : 234,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 12,
  "department_name" : "Нейрохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кримський В.С.",
  "personal_surname" : "Кримський",
  "personal_name" : "Віктор",
  "personal_patronymic" : "Станіславович",
  "personal_id" : 235,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 12,
  "department_name" : "Нейрохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Мороз О.А.",
  "personal_surname" : "Мороз",
  "personal_name" : "Олександр",
  "personal_patronymic" : "Анатолійович",
  "personal_id" : 236,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 12,
  "department_name" : "Нейрохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Чернецький В.В.",
  "personal_surname" : "Чернецький",
  "personal_name" : "Вадим",
  "personal_patronymic" : "Віталійович",
  "personal_id" : 237,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 12,
  "department_name" : "Нейрохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Лозинський А.В.",
  "personal_surname" : "Лозинський",
  "personal_name" : "Анатолій",
  "personal_patronymic" : "Валерійович",
  "personal_id" : 238,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 12,
  "department_name" : "Нейрохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Стецьків Т.П.",
  "personal_surname" : "Стецьків",
  "personal_name" : "Тетяна",
  "personal_patronymic" : "Петрівна",
  "personal_id" : 245,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 12,
  "department_name" : "Нейрохірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Білоус Л.М.",
  "personal_surname" : "Білоус",
  "personal_name" : "Лідія",
  "personal_patronymic" : "Михайлівна",
  "personal_id" : 136,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 13,
  "department_name" : "Нефрологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кушнір Н.І.",
  "personal_surname" : "Кушнір",
  "personal_name" : "Наталія",
  "personal_patronymic" : "Іванівна",
  "personal_id" : 135,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 13,
  "department_name" : "Нефрологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Тоцька О.Л.",
  "personal_surname" : "Тоцька",
  "personal_name" : "Олена",
  "personal_patronymic" : "Леонідівна",
  "personal_id" : 137,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 13,
  "department_name" : "Нефрологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Грановська Г.В.",
  "personal_surname" : "Грановська",
  "personal_name" : "Галина",
  "personal_patronymic" : "Віталівна",
  "personal_id" : 2700,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 13,
  "department_name" : "Нефрологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Алешко Н.Ю.",
  "personal_surname" : "Алешко",
  "personal_name" : "Наталя",
  "personal_patronymic" : "Юліанівна",
  "personal_id" : 2713,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 13,
  "department_name" : "Нефрологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Максімов С.Л.",
  "personal_surname" : "Максімов",
  "personal_name" : "Сергій",
  "personal_patronymic" : "Леонідович",
  "personal_id" : 183,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 14,
  "department_name" : "Опікове",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Каритун Н.П.",
  "personal_surname" : "Каритун",
  "personal_name" : "Наталія",
  "personal_patronymic" : "Петрівна",
  "personal_id" : 188,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 14,
  "department_name" : "Опікове",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кабачинський М.К.",
  "personal_surname" : "Кабачинський",
  "personal_name" : "Максим",
  "personal_patronymic" : "Констянтинович",
  "personal_id" : 190,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 14,
  "department_name" : "Опікове",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Вакулено В.О.",
  "personal_surname" : "Вакулено",
  "personal_name" : "Василь",
  "personal_patronymic" : "Олександрович",
  "personal_id" : 192,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 14,
  "department_name" : "Опікове",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Прозорський І.В.",
  "personal_surname" : "Прозорський",
  "personal_name" : "Іван",
  "personal_patronymic" : "Володимирович",
  "personal_id" : 198,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 14,
  "department_name" : "Опікове",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Пацаранюк О.Д.",
  "personal_surname" : "Пацаранюк",
  "personal_name" : "Олександр",
  "personal_patronymic" : "Дмитрович",
  "personal_id" : 250,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 14,
  "department_name" : "Опікове",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Хуторцова О.А.",
  "personal_surname" : "Хуторцова",
  "personal_name" : "Оксана",
  "personal_patronymic" : "Анатоліївна",
  "personal_id" : 251,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 14,
  "department_name" : "Опікове",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Марущак В.П.",
  "personal_surname" : "Марущак",
  "personal_name" : "Віталій",
  "personal_patronymic" : "Пилипович",
  "personal_id" : 253,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 15,
  "department_name" : "Ортопедичне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кикилик В.М.",
  "personal_surname" : "Кикилик",
  "personal_name" : "Володимир",
  "personal_patronymic" : "Миколайович",
  "personal_id" : 254,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 15,
  "department_name" : "Ортопедичне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Зав'ялець І.Т.",
  "personal_surname" : "Зав'ялець",
  "personal_name" : "Іван",
  "personal_patronymic" : "Тодорович",
  "personal_id" : 255,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 15,
  "department_name" : "Ортопедичне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Машевський А.С.",
  "personal_surname" : "Машевський",
  "personal_name" : "Андрій",
  "personal_patronymic" : "Станіславович",
  "personal_id" : 256,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 15,
  "department_name" : "Ортопедичне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Марущак В.В.",
  "personal_surname" : "Марущак",
  "personal_name" : "Віталій",
  "personal_patronymic" : "Віталійович",
  "personal_id" : 257,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 15,
  "department_name" : "Ортопедичне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Зав'ялець Л.І.",
  "personal_surname" : "Зав'ялець",
  "personal_name" : "Любомир",
  "personal_patronymic" : "Іванович",
  "personal_id" : 258,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 15,
  "department_name" : "Ортопедичне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Габінет В.Д.",
  "personal_surname" : "Габінет",
  "personal_name" : "Віталій",
  "personal_patronymic" : "Дмитрович",
  "personal_id" : 259,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 15,
  "department_name" : "Ортопедичне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Витвицький В.Б.",
  "personal_surname" : "Витвицький",
  "personal_name" : "Василь",
  "personal_patronymic" : "Богданович",
  "personal_id" : 260,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 15,
  "department_name" : "Ортопедичне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Загродський О.В.",
  "personal_surname" : "Загродський",
  "personal_name" : "Олександр",
  "personal_patronymic" : "Вікторович",
  "personal_id" : 2652,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 15,
  "department_name" : "Ортопедичне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Курило І.В.",
  "personal_surname" : "Курило",
  "personal_name" : "Ігор",
  "personal_patronymic" : "Віталійович",
  "personal_id" : 2656,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 15,
  "department_name" : "Ортопедичне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Лукаш К.В.",
  "personal_surname" : "Лукаш",
  "personal_name" : "Констянтин",
  "personal_patronymic" : "Володимирович",
  "personal_id" : 2657,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 15,
  "department_name" : "Ортопедичне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Курило І.І.",
  "personal_surname" : "Курило",
  "personal_name" : "Ігор",
  "personal_patronymic" : "Іванович",
  "personal_id" : 2664,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 15,
  "department_name" : "Ортопедичне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Мельник Л.П.",
  "personal_surname" : "Мельник",
  "personal_name" : "Леонід",
  "personal_patronymic" : "Петрович",
  "personal_id" : 2709,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 15,
  "department_name" : "Ортопедичне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Дарманська І.А.",
  "personal_surname" : "Дарманська",
  "personal_name" : "Ірина",
  "personal_patronymic" : "Анатоліївна",
  "personal_id" : 286,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 16,
  "department_name" : "Офтальмологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кульбаба О.Г.",
  "personal_surname" : "Кульбаба",
  "personal_name" : "Олександр",
  "personal_patronymic" : "Григорович",
  "personal_id" : 287,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 16,
  "department_name" : "Офтальмологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Козак І.І.",
  "personal_surname" : "Козак",
  "personal_name" : "Ірина",
  "personal_patronymic" : "Іванівна",
  "personal_id" : 288,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 16,
  "department_name" : "Офтальмологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Каплінська Л.В.",
  "personal_surname" : "Каплінська",
  "personal_name" : "Людмила",
  "personal_patronymic" : "Василівна",
  "personal_id" : 289,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 16,
  "department_name" : "Офтальмологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кириченко О.В.",
  "personal_surname" : "Кириченко",
  "personal_name" : "Ольга",
  "personal_patronymic" : "Володимирівна",
  "personal_id" : 291,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 16,
  "department_name" : "Офтальмологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Шамаріна І.Ю.",
  "personal_surname" : "Шамаріна",
  "personal_name" : "Ірина",
  "personal_patronymic" : "Юріївна",
  "personal_id" : 290,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 16,
  "department_name" : "Офтальмологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Філатова Т.В.",
  "personal_surname" : "Філатова",
  "personal_name" : "Тетяна",
  "personal_patronymic" : "Вікторівна",
  "personal_id" : 292,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 16,
  "department_name" : "Офтальмологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Коломієць О.В.",
  "personal_surname" : "Коломієць",
  "personal_name" : "Ольга",
  "personal_patronymic" : "Володимирівна",
  "personal_id" : 293,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 16,
  "department_name" : "Офтальмологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Ференс Т.В.",
  "personal_surname" : "Ференс",
  "personal_name" : "Тетяна",
  "personal_patronymic" : "Віталіївна",
  "personal_id" : 2647,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 16,
  "department_name" : "Офтальмологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Пірожок  Л.І.",
  "personal_surname" : "Пірожок ",
  "personal_name" : "Ларіса ",
  "personal_patronymic" : "Іванівна ",
  "personal_id" : 2650,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 16,
  "department_name" : "Офтальмологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Пірожок Л.І.",
  "personal_surname" : "Пірожок",
  "personal_name" : "Лариса",
  "personal_patronymic" : "Іванівна",
  "personal_id" : 279,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 16,
  "department_name" : "Офтальмологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Івахов П.Ю.",
  "personal_surname" : "Івахов",
  "personal_name" : "Павло",
  "personal_patronymic" : "Юрійович",
  "personal_id" : 148,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 19,
  "department_name" : "Приймальне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Михайленко Ю.О.",
  "personal_surname" : "Михайленко",
  "personal_name" : "Юлія",
  "personal_patronymic" : "Олександрівна",
  "personal_id" : 149,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 19,
  "department_name" : "Приймальне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кушнір І.А.",
  "personal_surname" : "Кушнір",
  "personal_name" : "Іванна",
  "personal_patronymic" : "Анатоліївна",
  "personal_id" : 150,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 19,
  "department_name" : "Приймальне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Доценко О.А.",
  "personal_surname" : "Доценко",
  "personal_name" : "Оксана",
  "personal_patronymic" : "Анатоліївна",
  "personal_id" : 205,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 19,
  "department_name" : "Приймальне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Галушко В.М.",
  "personal_surname" : "Галушко",
  "personal_name" : "Василь",
  "personal_patronymic" : "Миколайович",
  "personal_id" : 277,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 20,
  "department_name" : "Проктологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Керничний В.В.",
  "personal_surname" : "Керничний",
  "personal_name" : "Віталій",
  "personal_patronymic" : "Володимирович",
  "personal_id" : 284,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 20,
  "department_name" : "Проктологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Янчук М.А.",
  "personal_surname" : "Янчук",
  "personal_name" : "Микола",
  "personal_patronymic" : "Андрійович",
  "personal_id" : 282,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 20,
  "department_name" : "Проктологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Пискливець М.В.",
  "personal_surname" : "Пискливець",
  "personal_name" : "Марія",
  "personal_patronymic" : "Віталіївна",
  "personal_id" : 152,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 21,
  "department_name" : "Пульмонологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Решетова Л.Д.",
  "personal_surname" : "Решетова",
  "personal_name" : "Людмила",
  "personal_patronymic" : "Денисівна",
  "personal_id" : 153,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 21,
  "department_name" : "Пульмонологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Ігнатова Л.Б.",
  "personal_surname" : "Ігнатова",
  "personal_name" : "Людмила",
  "personal_patronymic" : "Борисівна",
  "personal_id" : 2698,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 21,
  "department_name" : "Пульмонологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Онишко В.В.",
  "personal_surname" : "Онишко",
  "personal_name" : "Віктор",
  "personal_patronymic" : "Волдимирович",
  "personal_id" : 2699,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 21,
  "department_name" : "Пульмонологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Білякова Л.А.",
  "personal_surname" : "Білякова",
  "personal_name" : "Лідія",
  "personal_patronymic" : "Андріївна",
  "personal_id" : 154,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 21,
  "department_name" : "Пульмонологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Бесараба М.Д.",
  "personal_surname" : "Бесараба",
  "personal_name" : "Микола",
  "personal_patronymic" : "Дмитрович",
  "personal_id" : 156,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Каритун В.В.",
  "personal_surname" : "Каритун",
  "personal_name" : "Володимир",
  "personal_patronymic" : "Володимирович",
  "personal_id" : 158,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Тоцький С.М.",
  "personal_surname" : "Тоцький",
  "personal_name" : "Сергій",
  "personal_patronymic" : "Миколайович",
  "personal_id" : 159,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Романовський В.П.",
  "personal_surname" : "Романовський",
  "personal_name" : "Віктор",
  "personal_patronymic" : "Петрович",
  "personal_id" : 160,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Погурало П.А.",
  "personal_surname" : "Погурало",
  "personal_name" : "Петро",
  "personal_patronymic" : "Адріянович",
  "personal_id" : 161,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Бахмацький І.Ф.",
  "personal_surname" : "Бахмацький",
  "personal_name" : "Ігор",
  "personal_patronymic" : "Феофанович",
  "personal_id" : 162,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Загоруйко В.К.",
  "personal_surname" : "Загоруйко",
  "personal_name" : "Валентин",
  "personal_patronymic" : "Кузьмич",
  "personal_id" : 163,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Бойчук П.А.",
  "personal_surname" : "Бойчук",
  "personal_name" : "Павло",
  "personal_patronymic" : "Анатолійович",
  "personal_id" : 164,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Цехмістер К.Ю.",
  "personal_surname" : "Цехмістер",
  "personal_name" : "Катерина",
  "personal_patronymic" : "Юріївна",
  "personal_id" : 167,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Ніколенко П.Є.",
  "personal_surname" : "Ніколенко",
  "personal_name" : "Петро",
  "personal_patronymic" : "Євгенович",
  "personal_id" : 168,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Машевський М.Й.",
  "personal_surname" : "Машевський",
  "personal_name" : "Микола",
  "personal_patronymic" : "Йосипович",
  "personal_id" : 169,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Урсол Н.Б.",
  "personal_surname" : "Урсол",
  "personal_name" : "Наталія",
  "personal_patronymic" : "Борисівна",
  "personal_id" : 124,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 1,
  "department_name" : "Алергологiчне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Корандо Н.В.",
  "personal_surname" : "Корандо",
  "personal_name" : "Наталія",
  "personal_patronymic" : "Вікторівна",
  "personal_id" : 2667,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 2,
  "department_name" : "Гінекологічне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Дунець О.Д.",
  "personal_surname" : "Дунець",
  "personal_name" : "Орися",
  "personal_patronymic" : "Дмитрівна",
  "personal_id" : 129,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 3,
  "department_name" : "Гастроентерологічне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Рехтман Г.Б.",
  "personal_surname" : "Рехтман",
  "personal_name" : "Георгій",
  "personal_patronymic" : "Борисович",
  "personal_id" : 2669,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 4,
  "department_name" : "Гематологічне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Одолінський С.С.",
  "personal_surname" : "Одолінський",
  "personal_name" : "Сергій",
  "personal_patronymic" : "Сергійович",
  "personal_id" : 175,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 5,
  "department_name" : "Детоксикації",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Карнаух К.В.",
  "personal_surname" : "Карнаух",
  "personal_name" : "Констянтин",
  "personal_patronymic" : "Володимирович",
  "personal_id" : 166,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 6,
  "department_name" : "ЕГ реанімація доросла",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Притуляк Л.В.",
  "personal_surname" : "Притуляк",
  "personal_name" : "Лариса",
  "personal_patronymic" : "Вікторівна",
  "personal_id" : 123,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 7,
  "department_name" : "ЕГПВ та Н",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Мукомела Л.І.",
  "personal_surname" : "Мукомела",
  "personal_name" : "Людмила",
  "personal_patronymic" : "Іванівна",
  "personal_id" : 2689,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 8,
  "department_name" : "Ендокринологія",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "КланцаА.І.",
  "personal_surname" : "Кланца",
  "personal_name" : "Андрій",
  "personal_patronymic" : "Іванович",
  "personal_id" : 2642,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 9,
  "department_name" : "Кардіохірургічне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Кланца А.І.",
  "personal_surname" : "Кланца",
  "personal_name" : "Андрій",
  "personal_patronymic" : "Іванович",
  "personal_id" : 264,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 9,
  "department_name" : "Кардіохірургічне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "КланцаА.І.",
  "personal_surname" : "Кланца",
  "personal_name" : "Андрій",
  "personal_patronymic" : "Іванович",
  "personal_id" : 2642,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 10,
  "department_name" : "Кардіореанімація",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Костюк О.В.",
  "personal_surname" : "Костюк",
  "personal_name" : "Олександр",
  "personal_patronymic" : "Володимирович",
  "personal_id" : 294,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 11,
  "department_name" : "Неврологічне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Левицький В.М.",
  "personal_surname" : "Левицький",
  "personal_name" : "Василь",
  "personal_patronymic" : "Михайлович",
  "personal_id" : 230,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 12,
  "department_name" : "Нейрохірургічне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Щербіна Н.В.",
  "personal_surname" : "Щербіна",
  "personal_name" : "Наталія",
  "personal_patronymic" : "Володимирівна",
  "personal_id" : 134,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 13,
  "department_name" : "Нефрологічне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Гринчук О.П.",
  "personal_surname" : "Гринчук",
  "personal_name" : "Олександр",
  "personal_patronymic" : "Петрович",
  "personal_id" : 249,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 14,
  "department_name" : "Опікове",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Павлішен Ю.І.",
  "personal_surname" : "Павлішен",
  "personal_name" : "Юрій",
  "personal_patronymic" : "Іванович",
  "personal_id" : 252,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 15,
  "department_name" : "Ортопедичне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Чернецький В.С.",
  "personal_surname" : "Чернецький",
  "personal_name" : "Віталій",
  "personal_patronymic" : "Северинович",
  "personal_id" : 285,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 16,
  "department_name" : "Офтальмологічне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Довгань Л.І.",
  "personal_surname" : "Довгань",
  "personal_name" : "Лариса",
  "personal_patronymic" : "Іванівна",
  "personal_id" : 146,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 19,
  "department_name" : "Приймальне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Балицький В.В.",
  "personal_surname" : "Балицький",
  "personal_name" : "Віталій",
  "personal_patronymic" : "Вікторович",
  "personal_id" : 280,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 20,
  "department_name" : "Проктологічне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Алешко А.П.",
  "personal_surname" : "Алешко",
  "personal_name" : "Анатолій",
  "personal_patronymic" : "Петрович",
  "personal_id" : 151,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 21,
  "department_name" : "Пульмонологічне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Логвін О.О.",
  "personal_surname" : "Логвін",
  "personal_name" : "Олена",
  "personal_patronymic" : "Олександрівна",
  "personal_id" : 247,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 19,
  "department_name" : "Приймальне",
  "position_id" : 4,
  "position_name" : "Середній мед. персонал"
}, {
  "personal_username" : "Новосядла І.М.",
  "personal_surname" : "Новосядла",
  "personal_name" : "Ірина",
  "personal_patronymic" : "Миколаївна",
  "personal_id" : 229,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 19,
  "department_name" : "Приймальне",
  "position_id" : 6,
  "position_name" : "Оператор"
}, {
  "personal_username" : "Приймальне",
  "personal_surname" : "Приймальне",
  "personal_name" : "7",
  "personal_patronymic" : "к",
  "personal_id" : 248,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 19,
  "department_name" : "Приймальне",
  "position_id" : 6,
  "position_name" : "Оператор"
}, {
  "personal_username" : "Загоруйко В.В.",
  "personal_surname" : "Загоруйко",
  "personal_name" : "Володимир",
  "personal_patronymic" : "Валентинович",
  "personal_id" : 170,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Маркова В.М.",
  "personal_surname" : "Маркова",
  "personal_name" : "Вікторія",
  "personal_patronymic" : "Михайлівна",
  "personal_id" : 171,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Крушельницький С.В.",
  "personal_surname" : "Крушельницький",
  "personal_name" : "Сергій",
  "personal_patronymic" : "Віталійович",
  "personal_id" : 172,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кирик Р.В.",
  "personal_surname" : "Кирик",
  "personal_name" : "Роман",
  "personal_patronymic" : "Володимирович",
  "personal_id" : 173,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Мельник А.В.",
  "personal_surname" : "Мельник",
  "personal_name" : "Андрій",
  "personal_patronymic" : "Віталійович",
  "personal_id" : 174,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Дема О.І.",
  "personal_surname" : "Дема",
  "personal_name" : "Олександр",
  "personal_patronymic" : "Іванович",
  "personal_id" : 184,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Вакулено В.О.",
  "personal_surname" : "Вакулено",
  "personal_name" : "Василь",
  "personal_patronymic" : "Олександрович",
  "personal_id" : 192,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Лиса Л.В.",
  "personal_surname" : "Лиса",
  "personal_name" : "Леся",
  "personal_patronymic" : "Володимирівна",
  "personal_id" : 195,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Андрухова Н.П.",
  "personal_surname" : "Андрухова",
  "personal_name" : "Неоніла",
  "personal_patronymic" : "Петрівна",
  "personal_id" : 199,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Каритун(мол) В.В.",
  "personal_surname" : "Каритун(мол)",
  "personal_name" : "Володимир",
  "personal_patronymic" : "Володимирович",
  "personal_id" : 246,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Кирик  Р.В.",
  "personal_surname" : "Кирик ",
  "personal_name" : "Роман",
  "personal_patronymic" : "Володимирович",
  "personal_id" : 308,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Криньов  К.Ю.",
  "personal_surname" : "Криньов ",
  "personal_name" : "Константин",
  "personal_patronymic" : "Юрійович",
  "personal_id" : 309,
  "personal_surgeon" : false,
  "personal_anesthetist" : true,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Криньов К.Ю.",
  "personal_surname" : "Криньов",
  "personal_name" : "Костянтин",
  "personal_patronymic" : "Юрійович",
  "personal_id" : 319,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 22,
  "department_name" : "Реанімаційне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Борисенко І.Д.",
  "personal_surname" : "Борисенко",
  "personal_name" : "Ірена",
  "personal_patronymic" : "Дмитрівна",
  "personal_id" : 125,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 23,
  "department_name" : "Ревматологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Закревська В.О.",
  "personal_surname" : "Закревська",
  "personal_name" : "Валентина",
  "personal_patronymic" : "Олексіїівна",
  "personal_id" : 126,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 23,
  "department_name" : "Ревматологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Шалавінська А.М.",
  "personal_surname" : "Шалавінська",
  "personal_name" : "Анна",
  "personal_patronymic" : "Михайлівна",
  "personal_id" : 128,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 23,
  "department_name" : "Ревматологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Тарасюк М.І.",
  "personal_surname" : "Тарасюк",
  "personal_name" : "Марина",
  "personal_patronymic" : "Ігорівна",
  "personal_id" : 127,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 23,
  "department_name" : "Ревматологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Лящук І.А.",
  "personal_surname" : "Лящук",
  "personal_name" : "Іванна",
  "personal_patronymic" : "Анатоліівна",
  "personal_id" : 2712,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 23,
  "department_name" : "Ревматологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Пискливець З.С.",
  "personal_surname" : "Пискливець",
  "personal_name" : "Зорян",
  "personal_patronymic" : "Степанович",
  "personal_id" : 240,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 24,
  "department_name" : "Судинної хірургії",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Решетов Л.М.",
  "personal_surname" : "Решетов",
  "personal_name" : "Леонід",
  "personal_patronymic" : "Михайлович",
  "personal_id" : 241,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 24,
  "department_name" : "Судинної хірургії",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Мартинюк В.Г.",
  "personal_surname" : "Мартинюк",
  "personal_name" : "Вадим",
  "personal_patronymic" : "Григорович",
  "personal_id" : 242,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 24,
  "department_name" : "Судинної хірургії",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Авраменко В.С.",
  "personal_surname" : "Авраменко",
  "personal_name" : "Владислав",
  "personal_patronymic" : "Сергійович",
  "personal_id" : 243,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 24,
  "department_name" : "Судинної хірургії",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Решетов Ю.Л.",
  "personal_surname" : "Решетов",
  "personal_name" : "Юрій",
  "personal_patronymic" : "Леонідович",
  "personal_id" : 244,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 24,
  "department_name" : "Судинної хірургії",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Прелепа О.І.",
  "personal_surname" : "Прелепа",
  "personal_name" : "Олексій",
  "personal_patronymic" : "Іванович",
  "personal_id" : 2653,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 25,
  "department_name" : "Торакальної хірургії",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Стрілець П.А.",
  "personal_surname" : "Стрілець",
  "personal_name" : "Петро",
  "personal_patronymic" : "Антонович",
  "personal_id" : 2654,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 25,
  "department_name" : "Торакальної хірургії",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Васильківський В.В.",
  "personal_surname" : "Васильківський",
  "personal_name" : "Віталій",
  "personal_patronymic" : "Вікторович",
  "personal_id" : 2655,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 25,
  "department_name" : "Торакальної хірургії",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Прилепа О.І.",
  "personal_surname" : "Прилепа",
  "personal_name" : "Олексій",
  "personal_patronymic" : "Іванович",
  "personal_id" : 2659,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 25,
  "department_name" : "Торакальної хірургії",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Корнійчук Ю.О.",
  "personal_surname" : "Корнійчук",
  "personal_name" : "Юрій",
  "personal_patronymic" : "Олексійович",
  "personal_id" : 2660,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 25,
  "department_name" : "Торакальної хірургії",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Калиновський В.В.",
  "personal_surname" : "Калиновський",
  "personal_name" : "В’ячеслав",
  "personal_patronymic" : "Валерійович",
  "personal_id" : 227,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 25,
  "department_name" : "Торакальної хірургії",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Чубар І.В.",
  "personal_surname" : "Чубар",
  "personal_name" : "Іван",
  "personal_patronymic" : "Вікторович",
  "personal_id" : 2716,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 25,
  "department_name" : "Торакальної хірургії",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Підмурняк О.О.",
  "personal_surname" : "Підмурняк",
  "personal_name" : "Олексій",
  "personal_patronymic" : "Олексійович",
  "personal_id" : 118,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 26,
  "department_name" : "Урологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Дрогоруб А.А.",
  "personal_surname" : "Дрогоруб",
  "personal_name" : "Андрій",
  "personal_patronymic" : "Анатолійович",
  "personal_id" : 122,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 26,
  "department_name" : "Урологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Бодько О.Є.",
  "personal_surname" : "Бодько",
  "personal_name" : "Олександр",
  "personal_patronymic" : "Євгенійович",
  "personal_id" : 207,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 26,
  "department_name" : "Урологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Яткевич Ю.В.",
  "personal_surname" : "Яткевич",
  "personal_name" : "Юрій",
  "personal_patronymic" : "Васильович",
  "personal_id" : 208,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 26,
  "department_name" : "Урологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Войцешин В.В.",
  "personal_surname" : "Войцешин",
  "personal_name" : "Володимир",
  "personal_patronymic" : "Васильович",
  "personal_id" : 209,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 26,
  "department_name" : "Урологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Монастирський В.М.",
  "personal_surname" : "Монастирський",
  "personal_name" : "Володимир",
  "personal_patronymic" : "Миколайович",
  "personal_id" : 210,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 26,
  "department_name" : "Урологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Алешко О.А.",
  "personal_surname" : "Алешко",
  "personal_name" : "Олександр",
  "personal_patronymic" : "Анатолійович",
  "personal_id" : 211,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 26,
  "department_name" : "Урологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Добровольський В.А.",
  "personal_surname" : "Добровольський",
  "personal_name" : "Вадим",
  "personal_patronymic" : "Анатолійович",
  "personal_id" : 212,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 26,
  "department_name" : "Урологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Боюк В.В.",
  "personal_surname" : "Боюк",
  "personal_name" : "Віктор",
  "personal_patronymic" : "Васильович",
  "personal_id" : 213,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 26,
  "department_name" : "Урологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Собчинський К.С.",
  "personal_surname" : "Собчинський",
  "personal_name" : "Костянтин",
  "personal_patronymic" : "Станіславович",
  "personal_id" : 214,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 26,
  "department_name" : "Урологічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Власов В.В.",
  "personal_surname" : "Власов",
  "personal_name" : "Василь",
  "personal_patronymic" : "Володимирович",
  "personal_id" : 217,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Подопригора Ю.А.",
  "personal_surname" : "Подопригора",
  "personal_name" : "Юрій",
  "personal_patronymic" : "Анатолійович",
  "personal_id" : 218,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Латинський Е.В.",
  "personal_surname" : "Латинський",
  "personal_name" : "Едуард",
  "personal_patronymic" : "Владиславович",
  "personal_id" : 219,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Тропарчук О.І.",
  "personal_surname" : "Тропарчук",
  "personal_name" : "Олег",
  "personal_patronymic" : "Іванович",
  "personal_id" : 220,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Приступа М.Є.",
  "personal_surname" : "Приступа",
  "personal_name" : "Микола",
  "personal_patronymic" : "Євгенійович",
  "personal_id" : 221,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Британчук Р.В.",
  "personal_surname" : "Британчук",
  "personal_name" : "Ростислав",
  "personal_patronymic" : "Васильович",
  "personal_id" : 222,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Петерчук О.Ф.",
  "personal_surname" : "Петерчук",
  "personal_name" : "Олег",
  "personal_patronymic" : "Федорович",
  "personal_id" : 223,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Сапожнік А.П.",
  "personal_surname" : "Сапожнік",
  "personal_name" : "Андрій",
  "personal_patronymic" : "Павлович",
  "personal_id" : 224,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Полоневич С.В.",
  "personal_surname" : "Полоневич",
  "personal_name" : "Сергій",
  "personal_patronymic" : "Васильович",
  "personal_id" : 225,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Костюк О.О.",
  "personal_surname" : "Костюк",
  "personal_name" : "Олександр",
  "personal_patronymic" : "Олександрович",
  "personal_id" : 226,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Калиновський В.В.",
  "personal_surname" : "Калиновський",
  "personal_name" : "В’ячеслав",
  "personal_patronymic" : "Валерійович",
  "personal_id" : 227,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Бабій І.В.",
  "personal_surname" : "Бабій",
  "personal_name" : "Ігор",
  "personal_patronymic" : "Володимирович",
  "personal_id" : 228,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Козак І.О.",
  "personal_surname" : "Козак",
  "personal_name" : "Іван",
  "personal_patronymic" : "Олександрович",
  "personal_id" : 261,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Міщенко Ф.П.",
  "personal_surname" : "Міщенко",
  "personal_name" : "Федір",
  "personal_patronymic" : "Пилипович",
  "personal_id" : 262,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Суходоля А.І.",
  "personal_surname" : "Суходоля",
  "personal_name" : "Анатолій",
  "personal_patronymic" : "Іванович",
  "personal_id" : 263,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Павлюк В.Б.",
  "personal_surname" : "Павлюк",
  "personal_name" : "Василь",
  "personal_patronymic" : "Богданович",
  "personal_id" : 307,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Микитюк С.Р.",
  "personal_surname" : "Микитюк",
  "personal_name" : "Святослав",
  "personal_patronymic" : "Ростиславович",
  "personal_id" : 2663,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Суходоля С.А.",
  "personal_surname" : "Суходоля",
  "personal_name" : "Сергій",
  "personal_patronymic" : "Анатолійович",
  "personal_id" : 2715,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Фелонюк Р.В.",
  "personal_surname" : "Фелонюк",
  "personal_name" : "Роман",
  "personal_patronymic" : "Васильович",
  "personal_id" : 2643,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 28,
  "department_name" : "Щелепно-лицьової хірургії",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Овчарук А.С.",
  "personal_surname" : "Овчарук",
  "personal_name" : "Андрій",
  "personal_patronymic" : "Степанович",
  "personal_id" : 2644,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 28,
  "department_name" : "Щелепно-лицьової хірургії",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Нагорний І.М.",
  "personal_surname" : "Нагорний",
  "personal_name" : "Іван",
  "personal_patronymic" : "Михайлович",
  "personal_id" : 2645,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 28,
  "department_name" : "Щелепно-лицьової хірургії",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "ренген р.р.",
  "personal_surname" : "ренген",
  "personal_name" : "ренген",
  "personal_patronymic" : "ренген",
  "personal_id" : 2714,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 29,
  "department_name" : "Поліклініка",
  "position_id" : 1,
  "position_name" : "Лікар"
}, {
  "personal_username" : "Урсол Н.Б.",
  "personal_surname" : "Урсол",
  "personal_name" : "Наталія",
  "personal_patronymic" : "Борисівна",
  "personal_id" : 124,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 23,
  "department_name" : "Ревматологічне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Міщенко Є.М.",
  "personal_surname" : "Міщенко",
  "personal_name" : "Євген",
  "personal_patronymic" : "Миколайович",
  "personal_id" : 239,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 24,
  "department_name" : "Судинної хірургії",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Франковский Р.Б.",
  "personal_surname" : "Франковский",
  "personal_name" : "Раймонд",
  "personal_patronymic" : "Броніславович",
  "personal_id" : 2651,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 25,
  "department_name" : "Торакальної хірургії",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Франковський Р.Б.",
  "personal_surname" : "Франковський",
  "personal_name" : "Раймонд",
  "personal_patronymic" : "Болеславович",
  "personal_id" : 2658,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 25,
  "department_name" : "Торакальної хірургії",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Собчинський С.А.",
  "personal_surname" : "Собчинський",
  "personal_name" : "Станіслав",
  "personal_patronymic" : "Антонович",
  "personal_id" : 155,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 26,
  "department_name" : "Урологічне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Підмурняк Ор.О.",
  "personal_surname" : "Підмурняк",
  "personal_name" : "Олександр",
  "personal_patronymic" : "Олексійович",
  "personal_id" : 216,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 27,
  "department_name" : "Хірургічне",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Компанієць Г.П.",
  "personal_surname" : "Компанієць",
  "personal_name" : "Ганна",
  "personal_patronymic" : "Панасівна",
  "personal_id" : 2646,
  "personal_surgeon" : true,
  "personal_anesthetist" : false,
  "department_id" : 28,
  "department_name" : "Щелепно-лицьової хірургії",
  "position_id" : 3,
  "position_name" : "Завідуючий відділення"
}, {
  "personal_username" : "Поліклініка",
  "personal_surname" : "Поліклініка",
  "personal_name" : "7",
  "personal_patronymic" : "к",
  "personal_id" : 276,
  "personal_surgeon" : false,
  "personal_anesthetist" : false,
  "department_id" : 29,
  "department_name" : "Поліклініка",
  "position_id" : 6,
  "position_name" : "Оператор"
} ]